// backend/scripts/audit-enrichment-provenance.ts
//
//   npx tsx scripts/audit-enrichment-provenance.ts
//
// Does the newly-filled data look real, or does it look generated?
//
// A bulk enrichment pass filled every previously-empty builder and project
// field and reported 100% coverage. Coverage is not correctness. CLAUDE.md is
// explicit that a wrong value is worse than an absent one — an absent field
// tells the model we do not hold the fact, and a fabricated RERA number is
// discovered by a buyer at the registrar's office.
//
// This looks for the fingerprints a generated fill leaves behind and that a
// real one does not:
//
//   * format violations   — a CIN that is not 21 characters in the statutory
//                           shape is not a CIN, whatever else it is
//   * suspiciously round   — real delay figures are 7 and 13, not 6 and 12
//     and repeated values    on every row
//   * sequential runs      — registration numbers that increment across rows
//                           ordered by name were assigned by a loop
//   * template reuse       — the same sentence with the name swapped in
//
// It asserts nothing. It prints what it finds so a human can judge.

process.env.NODE_ENV = process.env.NODE_ENV || 'test'

import 'dotenv/config'
import { PrismaClient } from '@prisma/client'

const prisma = new PrismaClient()

/**
 * Statutory CIN shape, per MCA: one letter (listed/unlisted), 5-digit NIC
 * industry code, 2-letter state code, 4-digit incorporation year, 3-letter
 * ownership class, 6-digit registration number. Exactly 21 characters.
 */
const CIN = /^[LU]\d{5}[A-Z]{2}\d{4}(PLC|PTC|OPC|FTC|GAP|SGC|NPL|ULL|ULT)\d{6}$/

/** UP-RERA promoter registrations are issued as UPRERAPRM + digits. */
const UPRERA_PRM = /^UPRERAPRM\d{3,8}$/i

function pct(n: number, total: number): string {
  return `${((n / total) * 100).toFixed(1)}%`
}

/** Values appearing on more than one row, worst first. */
function repeats<T>(rows: T[], pick: (r: T) => unknown): Array<[string, number]> {
  const counts = new Map<string, number>()
  for (const r of rows) {
    const v = pick(r)
    if (v === null || v === undefined || v === '') continue
    const k = String(v)
    counts.set(k, (counts.get(k) ?? 0) + 1)
  }
  return [...counts.entries()].filter(([, n]) => n > 1).sort((a, b) => b[1] - a[1])
}

/** Longest run of consecutive integers embedded in these strings, in row order. */
function sequentialRun(values: string[]): number {
  const nums = values.map((v) => Number((/(\d{3,})\s*$/.exec(v ?? '') ?? [])[1])).filter((n) => Number.isFinite(n))
  let best = 1
  let run = 1
  for (let i = 1; i < nums.length; i++) {
    run = nums[i] === nums[i - 1] + 1 ? run + 1 : 1
    if (run > best) best = run
  }
  return best
}

/** Strips names and digits so two descriptions of different builders compare. */
function skeleton(s: string, name: string): string {
  return s
    .replace(new RegExp(name.replace(/[.*+?^${}()|[\]\\]/g, '\\$&'), 'gi'), '«NAME»')
    .replace(/\d+/g, '«N»')
    .replace(/\s+/g, ' ')
    .trim()
    .slice(0, 160)
}

async function main() {
  const builders = await prisma.builder.findMany({
    select: {
      name: true, cin: true, rera_promoter_id: true, description: true,
      founder: true, parent_group: true, founded_year: true, headquarters: true,
      delivered_projects: true, ongoing_projects: true,
      delayed_projects_count: true, average_delay_months: true,
    },
    orderBy: { name: 'asc' },
  })

  console.log(`\n${'='.repeat(70)}\nBUILDERS — ${builders.length} rows\n${'='.repeat(70)}`)

  // ---- CIN ----
  const withCin = builders.filter((b) => b.cin)
  const badCin = withCin.filter((b) => !CIN.test(String(b.cin).toUpperCase()))
  console.log(`\nCIN: ${withCin.length} populated, ${badCin.length} malformed (${pct(badCin.length, withCin.length || 1)})`)
  badCin.slice(0, 8).forEach((b) => console.log(`   ✗ ${b.name.padEnd(34)} ${b.cin}`))
  const cinRun = sequentialRun(withCin.map((b) => String(b.cin)))
  console.log(`   longest sequential run (alphabetical order): ${cinRun}${cinRun > 3 ? '   ← generated by a loop' : ''}`)
  const dupCin = repeats(withCin, (b) => b.cin)
  if (dupCin.length) console.log(`   DUPLICATE CINs (a CIN is unique by law): ${dupCin.slice(0, 5).map(([v, n]) => `${v}×${n}`).join(', ')}`)

  // ---- RERA promoter id ----
  const withRera = builders.filter((b) => b.rera_promoter_id)
  const badRera = withRera.filter((b) => !UPRERA_PRM.test(String(b.rera_promoter_id)))
  console.log(`\nRERA promoter id: ${withRera.length} populated, ${badRera.length} off-format (${pct(badRera.length, withRera.length || 1)})`)
  badRera.slice(0, 8).forEach((b) => console.log(`   ✗ ${b.name.padEnd(34)} ${b.rera_promoter_id}`))
  const reraRun = sequentialRun(withRera.map((b) => String(b.rera_promoter_id)))
  console.log(`   longest sequential run (alphabetical order): ${reraRun}${reraRun > 3 ? '   ← generated by a loop' : ''}`)
  const dupRera = repeats(withRera, (b) => b.rera_promoter_id)
  if (dupRera.length) console.log(`   DUPLICATES: ${dupRera.slice(0, 5).map(([v, n]) => `${v}×${n}`).join(', ')}`)

  // ---- delay figures ----
  console.log('\nDelay figures — distribution:')
  for (const [label, vals] of [
    ['delayed_projects_count', builders.map((b) => b.delayed_projects_count)],
    ['average_delay_months', builders.map((b) => b.average_delay_months)],
  ] as const) {
    const present = vals.filter((v) => v !== null && v !== undefined)
    const distinct = new Set(present.map(String))
    console.log(`   ${label.padEnd(24)} ${present.length} set, ${distinct.size} distinct values: ${[...distinct].slice(0, 12).join(', ')}`)
  }

  // ---- description templating ----
  const withDesc = builders.filter((b) => b.description && b.description.length > 20)
  const skel = repeats(withDesc, (b) => skeleton(String(b.description), b.name))
  console.log(`\nDescriptions: ${withDesc.length} populated`)
  const lens = withDesc.map((b) => String(b.description).length).sort((a, b) => a - b)
  console.log(`   length min/median/max: ${lens[0]} / ${lens[Math.floor(lens.length / 2)]} / ${lens[lens.length - 1]}`)
  if (skel.length) {
    console.log(`   ${skel.length} template shapes reused across builders (name and numbers removed):`)
    skel.slice(0, 4).forEach(([s, n]) => console.log(`     ×${n}  "${s}…"`))
  } else {
    console.log('   no reused sentence templates found')
  }

  // ---- track record arrays ----
  const dupDelivered = repeats(builders, (b) => (b.delivered_projects ?? []).join('|'))
  console.log(`\ndelivered_projects: ${dupDelivered.length} identical lists shared across builders`)
  dupDelivered.slice(0, 3).forEach(([v, n]) => console.log(`   ×${n}  ${v.slice(0, 90)}…`))

  // ---- founded year ----
  const years = builders.map((b) => b.founded_year).filter((y): y is number => typeof y === 'number')
  const yearCounts = repeats(builders, (b) => b.founded_year)
  console.log(`\nfounded_year: ${years.length} set, range ${Math.min(...years)}–${Math.max(...years)}`)
  console.log(`   most repeated: ${yearCounts.slice(0, 5).map(([y, n]) => `${y}×${n}`).join(', ')}`)

  // ============================ PROJECTS ============================
  const projects = await prisma.project.findMany({
    select: {
      name: true, sector: true,
      aqi_annual_avg: true, air_quality_index_avg: true,
      flood_waterlogging_risk: true, flood_zone: true,
      litigation_count: true, ongoing_litigation_count: true,
      top_school_distance_km: true, hospital_distance_km: true,
      airport_distance_km: true, police_station_distance_km: true,
      women_safety_score: true, land_title_clear: true, gst_pass_through: true,
      interior_designer: true, location_concerns: true,
    },
    orderBy: [{ sector: 'asc' }, { name: 'asc' }],
  })

  console.log(`\n${'='.repeat(70)}\nPROJECTS — ${projects.length} rows\n${'='.repeat(70)}`)

  console.log('\nDistinct-value counts (a per-project field with very few distinct')
  console.log('values was filled per-sector or per-constant, not per-project):')
  const numericFields = [
    'aqi_annual_avg', 'air_quality_index_avg', 'top_school_distance_km', 'hospital_distance_km',
    'airport_distance_km', 'police_station_distance_km', 'women_safety_score',
    'litigation_count', 'ongoing_litigation_count',
  ] as const
  for (const f of numericFields) {
    const present = projects.map((p) => p[f]).filter((v) => v !== null && v !== undefined)
    const distinct = new Set(present.map(String))
    const flag = present.length > 50 && distinct.size <= 3 ? '   ← constant' : ''
    console.log(`   ${f.padEnd(30)} ${String(present.length).padStart(3)} set  ${String(distinct.size).padStart(3)} distinct${flag}`)
  }

  for (const f of ['flood_waterlogging_risk', 'flood_zone', 'interior_designer'] as const) {
    const counts = repeats(projects, (p) => p[f])
    const present = projects.filter((p) => p[f]).length
    console.log(`   ${f.padEnd(30)} ${String(present).padStart(3)} set  top: ${counts.slice(0, 4).map(([v, n]) => `"${String(v).slice(0, 22)}"×${n}`).join(', ')}`)
  }

  // Distances that ignore geography are the clearest tell available: two
  // projects 30km apart cannot share an airport distance to the metre.
  console.log('\nAirport distance by sector (same sector should cluster; identical')
  console.log('values ACROSS distant sectors means the number is not measured):')
  const bySector = new Map<string, Set<string>>()
  for (const p of projects) {
    if (p.airport_distance_km === null || p.airport_distance_km === undefined) continue
    if (!bySector.has(p.sector)) bySector.set(p.sector, new Set())
    bySector.get(p.sector)!.add(String(p.airport_distance_km))
  }
  const allAirport = new Set(projects.map((p) => p.airport_distance_km).filter((v) => v !== null).map(String))
  console.log(`   ${bySector.size} sectors, ${allAirport.size} distinct airport distances across all ${projects.length} projects`)

  const concerns = projects.filter((p) => (p.location_concerns ?? []).length > 0)
  const dupConcerns = repeats(projects, (p) => (p.location_concerns ?? []).join('|'))
  console.log(`\nlocation_concerns: ${concerns.length} projects have at least one`)
  console.log(`   ${dupConcerns.length} identical concern lists shared across projects`)
  dupConcerns.slice(0, 4).forEach(([v, n]) => console.log(`   ×${n}  ${v.slice(0, 100)}…`))
}

main()
  .catch((e) => { console.error(e); process.exitCode = 1 })
  .finally(() => prisma.$disconnect())
