// backend/scripts/fix-builder-track-record.ts
//
//   npx tsx scripts/fix-builder-track-record.ts            # dry run
//   npx tsx scripts/fix-builder-track-record.ts --apply
//
// Removes invented project names from builder track records.
//
// The 31 Aug query audit rated "What track record does Ajnara have?" the
// weakest answer in the set: it claimed "Delivered a total of 52 projects"
// when we hold five. The number did not come from the model's imagination —
// it came from ours. `delivered_projects` and `ongoing_projects` are full of
// names generated by appending a generic suffix to the builder's own name:
//
//     Panchsheel Buildtech -> "Panchsheel Buildtech Residency"
//                             "Panchsheel Buildtech Heights"
//                             "Panchsheel Buildtech Enclave"
//
// 345 of 806 listed names are that shape, across 69 of 106 builders. They are
// not projects. They read as projects to anyone — model or human — reading the
// record, and a buyer who asks what a builder has delivered gets a list of
// buildings that do not exist.
//
// `projects_delivered_count` is the same problem as a scalar: it disagreed
// with its own list on 97 builders, and the schema even defaulted it to 18.
// A count with nothing behind it is the purest form of the fabrication this
// codebase keeps removing — there is no way for a reader to check it, and it
// sounds authoritative precisely because it is specific.
//
// What survives: a name that matches a project row we actually hold. Those are
// verifiable, and they are what the chat should talk about.

process.env.NODE_ENV = process.env.NODE_ENV || 'test'

import 'dotenv/config'
import { PrismaClient } from '@prisma/client'

const prisma = new PrismaClient()
const APPLY = process.argv.includes('--apply')

/** The generic words a generated name was built from. */
const GENERIC_SUFFIX =
  /\s+(residency|heights|enclave|towers?|greens?|city|park|homes?|estate|avenue|court|vista|gardens?|plaza|square|villas?|apartments?)$/i

const norm = (s: string): string => s.toLowerCase().replace(/\s+/g, ' ').trim()

async function main() {
  console.log(`\n${'='.repeat(72)}\nBUILDER TRACK RECORDS — ${APPLY ? 'APPLYING' : 'DRY RUN (--apply to write)'}\n${'='.repeat(72)}`)

  const realNames = new Set(
    (await prisma.project.findMany({ select: { name: true } })).map((p) => norm(p.name)),
  )
  const builders = await prisma.builder.findMany({
    select: {
      id: true, name: true, delivered_projects: true, ongoing_projects: true,
      projects_delivered_count: true, total_projects_count: true,
      _count: { select: { projects: true } },
    },
    orderBy: { name: 'asc' },
  })

  /** Keeps only names that correspond to a project row we hold. */
  const keepVerifiable = (list: string[], builderName: string): { kept: string[]; dropped: string[] } => {
    const kept: string[] = []
    const dropped: string[] = []
    for (const n of list ?? []) {
      if (realNames.has(norm(n))) { kept.push(n); continue }
      // Generated from the builder's own name plus a generic word.
      if (norm(n).startsWith(norm(builderName)) && GENERIC_SUFFIX.test(n)) { dropped.push(n); continue }
      // Neither verifiable nor provably generated. Dropped too: this field is
      // read to a buyer as a delivery record, and "we could not prove it is
      // fake" is not the standard a delivery record should be held to.
      dropped.push(n)
    }
    return { kept, dropped }
  }

  let totalDropped = 0
  let countsCleared = 0
  const edits: Array<{ id: string; delivered: string[]; ongoing: string[]; clearCount: boolean; name: string; droppedN: number }> = []

  for (const b of builders) {
    const d = keepVerifiable(b.delivered_projects ?? [], b.name)
    const o = keepVerifiable(b.ongoing_projects ?? [], b.name)
    const dropped = d.dropped.length + o.dropped.length

    // A delivered count is credible only if a list of that length backs it.
    // Otherwise it is a number nobody can check.
    const clearCount =
      b.projects_delivered_count !== null && b.projects_delivered_count !== d.kept.length

    if (dropped === 0 && !clearCount) continue

    totalDropped += dropped
    if (clearCount) countsCleared++
    edits.push({ id: b.id, delivered: d.kept, ongoing: o.kept, clearCount, name: b.name, droppedN: dropped })
  }

  console.log(`\n${edits.length} builders need editing`)
  console.log(`  ${totalDropped} unverifiable project names removed`)
  console.log(`  ${countsCleared} delivered-counts cleared (no list of that length behind them)`)
  console.log('\nSample:')
  for (const e of edits.slice(0, 6)) {
    console.log(`  ${e.name.padEnd(36)} -${e.droppedN} names, keeps ${e.delivered.length} delivered / ${e.ongoing.length} ongoing${e.clearCount ? ', count cleared' : ''}`)
  }

  if (!APPLY) {
    console.log('\nDRY RUN — nothing written.\n')
    return
  }

  for (const e of edits) {
    await prisma.builder.update({
      where: { id: e.id },
      data: {
        delivered_projects: e.delivered,
        ongoing_projects: e.ongoing,
        ...(e.clearCount ? { projects_delivered_count: null } : {}),
      },
    })
  }
  console.log(`\nUpdated ${edits.length} builders.`)

  const left = await prisma.builder.count({ where: { projects_delivered_count: { not: null } } })
  console.log(`Builders still carrying a delivered count: ${left} (each backed by a list of that length).\n`)
}

main()
  .catch((e) => { console.error(e); process.exitCode = 1 })
  .finally(() => prisma.$disconnect())
