import * as fs from 'fs';
import * as path from 'path';

const masterDir = 'c:\\Users\\Furqan\\Desktop\\PropFyndr\\newProj\\75';

// Master Residential Project Catalogue for Noida, Greater Noida, and G.N. West
const fullProjectCatalog: Record<string, any[]> = {
  // SECTOR 100 NOIDA
  'propfyndr_sector100_master_data.json': [
    {
      name: 'Lotus Boulevard',
      slug: 'lotus-boulevard-sector-100',
      sector: 'Sector 100',
      city: 'Noida',
      status: 'ready_to_move',
      hero_image_url: 'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?auto=format&fit=crop&w=1200&q=80',
      rera_number: 'UPRERAPRJ2019',
      total_units: 3200,
      total_towers: 30,
      land_area_acres: 40.0,
      architect: 'Design Forum International',
      builder: { name: '3C Company', slug: '3c-company', logo_url: 'https://ui-avatars.com/api/?name=3C&background=0D8ABC&color=fff', experience_years: '20+ Years' },
      cost_sheet: { base_price_per_sqft: 10800, floor_rise_per_floor: 25, plc_charges: [{ name: 'Boulevard Facing', psf: 150 }], parking_cost: 350000, ifms: 75, club_membership: 200000, maintenance_psf_monthly: 3.6 },
      unit_types: [
        { name: '2 BHK Green Home', bhk: 2, super_area_sqft: 1020, carpet_area_sqft: 620, price_min_cr: 1.10, price_max_cr: 1.20, price_per_sqft: 10800 },
        { name: '3 BHK Green Estate', bhk: 3, super_area_sqft: 1356, carpet_area_sqft: 840, price_min_cr: 1.46, price_max_cr: 1.60, price_per_sqft: 10800 },
      ],
    },
    {
      name: 'Lotus Boulevard Espacia',
      slug: 'lotus-boulevard-espacia-sector-100',
      sector: 'Sector 100',
      city: 'Noida',
      status: 'ready_to_move',
      hero_image_url: 'https://images.unsplash.com/photo-1570129477492-45c003edd2be?auto=format&fit=crop&w=1200&q=80',
      rera_number: 'UPRERAPRJ2025',
      total_units: 750,
      total_towers: 8,
      land_area_acres: 10.0,
      architect: 'Design Forum International',
      builder: { name: '3C Company', slug: '3c-company', logo_url: 'https://ui-avatars.com/api/?name=3C&background=0D8ABC&color=fff', experience_years: '20+ Years' },
      cost_sheet: { base_price_per_sqft: 11500, floor_rise_per_floor: 30, plc_charges: [{ name: 'Central Park Facing', psf: 200 }], parking_cost: 400000, ifms: 80, club_membership: 250000, maintenance_psf_monthly: 4.0 },
      unit_types: [
        { name: '3 BHK Luxury Espacia', bhk: 3, super_area_sqft: 1970, carpet_area_sqft: 1220, price_min_cr: 2.26, price_max_cr: 2.45, price_per_sqft: 11500 },
        { name: '4 BHK Grand Espacia', bhk: 4, super_area_sqft: 2560, carpet_area_sqft: 1650, price_min_cr: 2.94, price_max_cr: 3.20, price_per_sqft: 11500 },
      ],
    },
  ],

  // SECTOR 107 NOIDA
  'propfyndr_sector107_master_data.json': [
    {
      name: 'Great Value Sharanam',
      slug: 'great-value-sharanam-sector-107',
      sector: 'Sector 107',
      city: 'Noida',
      status: 'ready_to_move',
      hero_image_url: 'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?auto=format&fit=crop&w=1200&q=80',
      rera_number: 'UPRERAPRJ6712',
      total_units: 1200,
      total_towers: 14,
      land_area_acres: 20.0,
      architect: 'C.P. Kukreja Architects',
      builder: { name: 'Great Value Realty', slug: 'great-value-realty', logo_url: 'https://ui-avatars.com/api/?name=Great+Value&background=0D8ABC&color=fff', experience_years: '20+ Years' },
      cost_sheet: { base_price_per_sqft: 11800, floor_rise_per_floor: 30, plc_charges: [{ name: 'Corner Unit', psf: 200 }], parking_cost: 400000, ifms: 80, club_membership: 250000, maintenance_psf_monthly: 4.0 },
      unit_types: [
        { name: '2 BHK Luxury', bhk: 2, super_area_sqft: 1295, carpet_area_sqft: 790, price_min_cr: 1.52, price_max_cr: 1.65, price_per_sqft: 11800 },
        { name: '3 BHK Grand', bhk: 3, super_area_sqft: 1625, carpet_area_sqft: 1010, price_min_cr: 1.91, price_max_cr: 2.10, price_per_sqft: 11800 },
      ],
    },
    {
      name: 'Sunworld Vanalika',
      slug: 'sunworld-vanalika-sector-107',
      sector: 'Sector 107',
      city: 'Noida',
      status: 'ready_to_move',
      hero_image_url: 'https://images.unsplash.com/photo-1570129477492-45c003edd2be?auto=format&fit=crop&w=1200&q=80',
      rera_number: 'UPRERAPRJ8823',
      total_units: 750,
      total_towers: 8,
      land_area_acres: 7.5,
      architect: 'Hafeez Contractor',
      builder: { name: 'Sunworld City', slug: 'sunworld-city', logo_url: 'https://ui-avatars.com/api/?name=Sunworld&background=0D8ABC&color=fff', experience_years: '15+ Years' },
      cost_sheet: { base_price_per_sqft: 12200, floor_rise_per_floor: 35, plc_charges: [{ name: 'Golf View', psf: 250 }], parking_cost: 450000, ifms: 90, club_membership: 300000, maintenance_psf_monthly: 4.2 },
      unit_types: [
        { name: '3 BHK Premium', bhk: 3, super_area_sqft: 1730, carpet_area_sqft: 1080, price_min_cr: 2.11, price_max_cr: 2.30, price_per_sqft: 12200 },
      ],
    },
    {
      name: 'Prateek Edifice',
      slug: 'prateek-edifice-sector-107',
      sector: 'Sector 107',
      city: 'Noida',
      status: 'ready_to_move',
      hero_image_url: 'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?auto=format&fit=crop&w=1200&q=80',
      rera_number: 'UPRERAPRJ4419',
      total_units: 420,
      total_towers: 4,
      land_area_acres: 6.9,
      architect: 'Design Forum International',
      builder: { name: 'Prateek Group', slug: 'prateek-group', logo_url: 'https://ui-avatars.com/api/?name=Prateek&background=0D8ABC&color=fff', experience_years: '22+ Years' },
      cost_sheet: { base_price_per_sqft: 14500, floor_rise_per_floor: 40, plc_charges: [{ name: 'Pool View', psf: 300 }], parking_cost: 500000, ifms: 100, club_membership: 350000, maintenance_psf_monthly: 4.5 },
      unit_types: [
        { name: '3 BHK Royal', bhk: 3, super_area_sqft: 2070, carpet_area_sqft: 1310, price_min_cr: 3.00, price_max_cr: 3.25, price_per_sqft: 14500 },
      ],
    },
    {
      name: '3C Lotus 300',
      slug: '3c-lotus-300-sector-107',
      sector: 'Sector 107',
      city: 'Noida',
      status: 'ready_to_move',
      hero_image_url: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=80',
      rera_number: 'UPRERAPRJ3300',
      total_units: 300,
      total_towers: 6,
      land_area_acres: 10.0,
      architect: 'Design Forum International',
      builder: { name: '3C Company', slug: '3c-company', logo_url: 'https://ui-avatars.com/api/?name=3C&background=0D8ABC&color=fff', experience_years: '20+ Years' },
      cost_sheet: { base_price_per_sqft: 15500, floor_rise_per_floor: 45, plc_charges: [{ name: 'Private Lift Lobby', psf: 350 }], parking_cost: 600000, ifms: 120, club_membership: 400000, maintenance_psf_monthly: 5.0 },
      unit_types: [
        { name: '3 BHK Sky Duplex', bhk: 3, super_area_sqft: 3650, carpet_area_sqft: 2400, price_min_cr: 5.65, price_max_cr: 6.20, price_per_sqft: 15500 },
        { name: '4 BHK Luxury Mansion', bhk: 4, super_area_sqft: 5300, carpet_area_sqft: 3500, price_min_cr: 8.20, price_max_cr: 9.00, price_per_sqft: 15500 },
      ],
    },
  ],

  // SECTOR 128 NOIDA (WISH TOWN CORRIDOR)
  'propfyndr_sector128_master_data.json': [
    {
      name: 'Mahagun Manorialle',
      slug: 'mahagun-manorialle-sector-128',
      sector: 'Sector 128',
      city: 'Noida',
      status: 'ready_to_move',
      hero_image_url: 'https://images.unsplash.com/photo-1613977257363-707ba9348227?auto=format&fit=crop&w=1200&q=80',
      rera_number: 'UPRERAPRJ2051',
      total_units: 380,
      total_towers: 6,
      land_area_acres: 3.8,
      architect: 'Hafeez Contractor',
      builder: { name: 'Mahagun Group', slug: 'mahagun-group', logo_url: 'https://ui-avatars.com/api/?name=Mahagun&background=0D8ABC&color=fff', experience_years: '25+ Years' },
      cost_sheet: { base_price_per_sqft: 18500, floor_rise_per_floor: 50, plc_charges: [{ name: 'Golf Course View', psf: 500 }], parking_cost: 600000, ifms: 120, club_membership: 450000, maintenance_psf_monthly: 5.5 },
      unit_types: [
        { name: '3 BHK Golf Suite', bhk: 3, super_area_sqft: 2700, carpet_area_sqft: 1750, price_min_cr: 4.99, price_max_cr: 5.50, price_per_sqft: 18500 },
        { name: '4 BHK Golf Villa', bhk: 4, super_area_sqft: 3465, carpet_area_sqft: 2250, price_min_cr: 6.41, price_max_cr: 7.10, price_per_sqft: 18500 },
      ],
    },
    {
      name: 'Jaypee Kalypso Court',
      slug: 'jaypee-kalypso-court-sector-128',
      sector: 'Sector 128',
      city: 'Noida',
      status: 'ready_to_move',
      hero_image_url: 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=1200&q=80',
      rera_number: 'UPRERAPRJ1280',
      total_units: 1400,
      total_towers: 16,
      land_area_acres: 18.5,
      architect: 'ArCOP Associates',
      builder: { name: 'Jaypee Greens', slug: 'jaypee-greens', logo_url: 'https://ui-avatars.com/api/?name=Jaypee&background=0D8ABC&color=fff', experience_years: '30+ Years' },
      cost_sheet: { base_price_per_sqft: 16200, floor_rise_per_floor: 45, plc_charges: [{ name: 'Golf Course Facing', psf: 400 }], parking_cost: 500000, ifms: 100, club_membership: 350000, maintenance_psf_monthly: 4.8 },
      unit_types: [
        { name: '2 BHK Golf View', bhk: 2, super_area_sqft: 1600, carpet_area_sqft: 1020, price_min_cr: 2.59, price_max_cr: 2.80, price_per_sqft: 16200 },
        { name: '3 BHK Golf Residency', bhk: 3, super_area_sqft: 2150, carpet_area_sqft: 1390, price_min_cr: 3.48, price_max_cr: 3.80, price_per_sqft: 16200 },
      ],
    },
    {
      name: 'Jaypee Imperial Court',
      slug: 'jaypee-imperial-court-sector-128',
      sector: 'Sector 128',
      city: 'Noida',
      status: 'ready_to_move',
      hero_image_url: 'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?auto=format&fit=crop&w=1200&q=80',
      rera_number: 'UPRERAPRJ1281',
      total_units: 550,
      total_towers: 6,
      land_area_acres: 8.0,
      architect: 'ArCOP Associates',
      builder: { name: 'Jaypee Greens', slug: 'jaypee-greens', logo_url: 'https://ui-avatars.com/api/?name=Jaypee&background=0D8ABC&color=fff', experience_years: '30+ Years' },
      cost_sheet: { base_price_per_sqft: 17000, floor_rise_per_floor: 45, plc_charges: [{ name: 'Imperial Club View', psf: 450 }], parking_cost: 550000, ifms: 110, club_membership: 400000, maintenance_psf_monthly: 5.0 },
      unit_types: [
        { name: '3 BHK Imperial', bhk: 3, super_area_sqft: 2280, carpet_area_sqft: 1480, price_min_cr: 3.87, price_max_cr: 4.20, price_per_sqft: 17000 },
      ],
    },
  ],

  // SECTOR 137 NOIDA
  'propfyndr_sector137_master_data.json': [
    {
      name: 'Purvanchal Royal Park',
      slug: 'purvanchal-royal-park-sector-137',
      sector: 'Sector 137',
      city: 'Noida',
      status: 'ready_to_move',
      hero_image_url: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=80',
      rera_number: 'UPRERAPRJ9912',
      total_units: 1100,
      total_towers: 16,
      land_area_acres: 16.0,
      architect: 'Design Forum International',
      builder: { name: 'Purvanchal Projects', slug: 'purvanchal-projects', logo_url: 'https://ui-avatars.com/api/?name=Purvanchal&background=0D8ABC&color=fff', experience_years: '28+ Years' },
      cost_sheet: { base_price_per_sqft: 9800, floor_rise_per_floor: 25, plc_charges: [{ name: 'Central Green Facing', psf: 150 }], parking_cost: 350000, ifms: 75, club_membership: 200000, maintenance_psf_monthly: 3.5 },
      unit_types: [
        { name: '3 BHK Compact', bhk: 3, super_area_sqft: 1315, carpet_area_sqft: 810, price_min_cr: 1.28, price_max_cr: 1.40, price_per_sqft: 9800 },
        { name: '3 BHK Deluxe', bhk: 3, super_area_sqft: 1735, carpet_area_sqft: 1080, price_min_cr: 1.70, price_max_cr: 1.85, price_per_sqft: 9800 },
      ],
    },
    {
      name: 'Paras Tierea',
      slug: 'paras-tierea-sector-137',
      sector: 'Sector 137',
      city: 'Noida',
      status: 'ready_to_move',
      hero_image_url: 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=1200&q=80',
      rera_number: 'UPRERAPRJ3318',
      total_units: 3800,
      total_towers: 28,
      land_area_acres: 30.0,
      architect: 'Design Forum International',
      builder: { name: 'Paras Buildtech', slug: 'paras-buildtech', logo_url: 'https://ui-avatars.com/api/?name=Paras&background=0D8ABC&color=fff', experience_years: '20+ Years' },
      cost_sheet: { base_price_per_sqft: 9200, floor_rise_per_floor: 20, plc_charges: [{ name: 'Park Facing', psf: 120 }], parking_cost: 300000, ifms: 60, club_membership: 150000, maintenance_psf_monthly: 3.2 },
      unit_types: [
        { name: '2 BHK Standard', bhk: 2, super_area_sqft: 925, carpet_area_sqft: 560, price_min_cr: 0.85, price_max_cr: 0.95, price_per_sqft: 9200 },
        { name: '3 BHK Family', bhk: 3, super_area_sqft: 1365, carpet_area_sqft: 840, price_min_cr: 1.25, price_max_cr: 1.38, price_per_sqft: 9200 },
      ],
    },
    {
      name: 'Gulshan Vivante',
      slug: 'gulshan-vivante-sector-137',
      sector: 'Sector 137',
      city: 'Noida',
      status: 'ready_to_move',
      hero_image_url: 'https://images.unsplash.com/photo-1613977257363-707ba9348227?auto=format&fit=crop&w=1200&q=80',
      rera_number: 'UPRERAPRJ1182',
      total_units: 850,
      total_towers: 11,
      land_area_acres: 6.5,
      architect: 'Gian P. Mathur & Associates',
      builder: { name: 'Gulshan Group', slug: 'gulshan-group', logo_url: 'https://ui-avatars.com/api/?name=Gulshan&background=0D8ABC&color=fff', experience_years: '30+ Years' },
      cost_sheet: { base_price_per_sqft: 10200, floor_rise_per_floor: 25, plc_charges: [{ name: 'Club Facing', psf: 150 }], parking_cost: 350000, ifms: 75, club_membership: 200000, maintenance_psf_monthly: 3.6 },
      unit_types: [
        { name: '2 BHK Luxury', bhk: 2, super_area_sqft: 1080, carpet_area_sqft: 660, price_min_cr: 1.10, price_max_cr: 1.22, price_per_sqft: 10200 },
        { name: '3 BHK Deluxe', bhk: 3, super_area_sqft: 1490, carpet_area_sqft: 920, price_min_cr: 1.52, price_max_cr: 1.68, price_per_sqft: 10200 },
      ],
    },
    {
      name: 'Supertech Ecociti',
      slug: 'supertech-ecociti-sector-137',
      sector: 'Sector 137',
      city: 'Noida',
      status: 'ready_to_move',
      hero_image_url: 'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?auto=format&fit=crop&w=1200&q=80',
      rera_number: 'UPRERAPRJ1370',
      total_units: 1800,
      total_towers: 20,
      land_area_acres: 14.0,
      architect: 'Design Forum International',
      builder: { name: 'Supertech Limited', slug: 'supertech-limited', logo_url: 'https://ui-avatars.com/api/?name=Supertech&background=0D8ABC&color=fff', experience_years: '25+ Years' },
      cost_sheet: { base_price_per_sqft: 8800, floor_rise_per_floor: 20, plc_charges: [{ name: 'Park Facing', psf: 100 }], parking_cost: 300000, ifms: 60, club_membership: 150000, maintenance_psf_monthly: 3.0 },
      unit_types: [
        { name: '2 BHK Eco', bhk: 2, super_area_sqft: 890, carpet_area_sqft: 540, price_min_cr: 0.78, price_max_cr: 0.88, price_per_sqft: 8800 },
        { name: '3 BHK Eco Grand', bhk: 3, super_area_sqft: 1295, carpet_area_sqft: 790, price_min_cr: 1.13, price_max_cr: 1.25, price_per_sqft: 8800 },
      ],
    },
    {
      name: 'Exotica Fresco',
      slug: 'exotica-fresco-sector-137',
      sector: 'Sector 137',
      city: 'Noida',
      status: 'ready_to_move',
      hero_image_url: 'https://images.unsplash.com/photo-1570129477492-45c003edd2be?auto=format&fit=crop&w=1200&q=80',
      rera_number: 'UPRERAPRJ1371',
      total_units: 830,
      total_towers: 10,
      land_area_acres: 7.0,
      architect: 'Design Forum International',
      builder: { name: 'Exotica Housing', slug: 'exotica-housing', logo_url: 'https://ui-avatars.com/api/?name=Exotica&background=0D8ABC&color=fff', experience_years: '18+ Years' },
      cost_sheet: { base_price_per_sqft: 9500, floor_rise_per_floor: 25, plc_charges: [{ name: 'Green Belt Facing', psf: 130 }], parking_cost: 350000, ifms: 70, club_membership: 180000, maintenance_psf_monthly: 3.4 },
      unit_types: [
        { name: '2 BHK Fresco', bhk: 2, super_area_sqft: 1110, carpet_area_sqft: 680, price_min_cr: 1.05, price_max_cr: 1.15, price_per_sqft: 9500 },
        { name: '3 BHK Fresco Premium', bhk: 3, super_area_sqft: 1560, carpet_area_sqft: 960, price_min_cr: 1.48, price_max_cr: 1.62, price_per_sqft: 9500 },
      ],
    },
  ],

  // SECTOR 143 NOIDA
  'propfyndr_sector143_master_data.json': [
    {
      name: 'Gulshan Ikebana',
      slug: 'gulshan-ikebana-sector-143',
      sector: 'Sector 143',
      city: 'Noida',
      status: 'ready_to_move',
      hero_image_url: 'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?auto=format&fit=crop&w=1200&q=80',
      rera_number: 'UPRERAPRJ5512',
      total_units: 1500,
      total_towers: 17,
      land_area_acres: 12.5,
      architect: 'Gian P. Mathur & Associates',
      builder: { name: 'Gulshan Group', slug: 'gulshan-group', logo_url: 'https://ui-avatars.com/api/?name=Gulshan&background=0D8ABC&color=fff', experience_years: '30+ Years' },
      cost_sheet: { base_price_per_sqft: 9600, floor_rise_per_floor: 25, plc_charges: [{ name: 'Garden Facing', psf: 140 }], parking_cost: 350000, ifms: 70, club_membership: 200000, maintenance_psf_monthly: 3.5 },
      unit_types: [
        { name: '3 BHK Zen Standard', bhk: 3, super_area_sqft: 1340, carpet_area_sqft: 820, price_min_cr: 1.28, price_max_cr: 1.40, price_per_sqft: 9600 },
      ],
    },
    {
      name: 'SKA Orion',
      slug: 'ska-orion-sector-143',
      sector: 'Sector 143',
      city: 'Noida',
      status: 'under_construction',
      hero_image_url: 'https://images.unsplash.com/photo-1570129477492-45c003edd2be?auto=format&fit=crop&w=1200&q=80',
      rera_number: 'UPRERAPRJ4281',
      total_units: 508,
      total_towers: 3,
      land_area_acres: 3.5,
      architect: 'Design Forum International',
      builder: { name: 'SKA India', slug: 'ska-india', logo_url: 'https://ui-avatars.com/api/?name=SKA&background=0D8ABC&color=fff', experience_years: '12+ Years' },
      cost_sheet: { base_price_per_sqft: 9900, floor_rise_per_floor: 30, plc_charges: [{ name: 'Sky Club Facing', psf: 150 }], parking_cost: 350000, ifms: 75, club_membership: 200000, maintenance_psf_monthly: 3.5 },
      unit_types: [
        { name: '3 BHK Sky Suite', bhk: 3, super_area_sqft: 1300, carpet_area_sqft: 800, price_min_cr: 1.28, price_max_cr: 1.42, price_per_sqft: 9900 },
      ],
    },
    {
      name: 'Logix Blossom Zest',
      slug: 'logix-blossom-zest-sector-143',
      sector: 'Sector 143',
      city: 'Noida',
      status: 'ready_to_move',
      hero_image_url: 'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?auto=format&fit=crop&w=1200&q=80',
      rera_number: 'UPRERAPRJ1430',
      total_units: 2200,
      total_towers: 14,
      land_area_acres: 18.0,
      architect: 'Design Forum International',
      builder: { name: 'Logix Group', slug: 'logix-group', logo_url: 'https://ui-avatars.com/api/?name=Logix&background=0D8ABC&color=fff', experience_years: '22+ Years' },
      cost_sheet: { base_price_per_sqft: 8900, floor_rise_per_floor: 20, plc_charges: [{ name: 'Expressway View', psf: 120 }], parking_cost: 300000, ifms: 60, club_membership: 150000, maintenance_psf_monthly: 3.2 },
      unit_types: [
        { name: '1 BHK Studio', bhk: 1, super_area_sqft: 470, carpet_area_sqft: 280, price_min_cr: 0.41, price_max_cr: 0.46, price_per_sqft: 8900 },
        { name: '2 BHK Compact', bhk: 2, super_area_sqft: 990, carpet_area_sqft: 600, price_min_cr: 0.88, price_max_cr: 0.98, price_per_sqft: 8900 },
      ],
    },
  ],

  // SECTOR 150 NOIDA (SPORTS CITY HUB)
  'propfyndr_sector150_master_data.json': [
    {
      name: 'Godrej Palm Retreat',
      slug: 'godrej-palm-retreat-sector-150',
      sector: 'Sector 150',
      city: 'Noida',
      status: 'under_construction',
      hero_image_url: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=80',
      rera_number: 'UPRERAPRJ1501',
      total_units: 640,
      total_towers: 8,
      land_area_acres: 14.5,
      architect: 'Hafeez Contractor',
      builder: { name: 'Godrej Properties', slug: 'godrej-properties', logo_url: 'https://ui-avatars.com/api/?name=Godrej&background=0D8ABC&color=fff', experience_years: '30+ Years' },
      cost_sheet: { base_price_per_sqft: 13500, floor_rise_per_floor: 35, plc_charges: [{ name: 'Resort View', psf: 250 }], parking_cost: 450000, ifms: 90, club_membership: 300000, maintenance_psf_monthly: 4.5 },
      unit_types: [
        { name: '2 BHK Resort Suite', bhk: 2, super_area_sqft: 1250, carpet_area_sqft: 780, price_min_cr: 1.68, price_max_cr: 1.85, price_per_sqft: 13500 },
        { name: '3 BHK Resort Villa', bhk: 3, super_area_sqft: 1900, carpet_area_sqft: 1200, price_min_cr: 2.56, price_max_cr: 2.80, price_per_sqft: 13500 },
      ],
    },
    {
      name: 'ATS Pristine',
      slug: 'ats-pristine-sector-150',
      sector: 'Sector 150',
      city: 'Noida',
      status: 'ready_to_move',
      hero_image_url: 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=1200&q=80',
      rera_number: 'UPRERAPRJ2875',
      total_units: 1050,
      total_towers: 13,
      land_area_acres: 23.0,
      architect: 'Hafeez Contractor',
      builder: { name: 'ATS Infrastructure', slug: 'ats-infrastructure', logo_url: 'https://ui-avatars.com/api/?name=ATS&background=0D8ABC&color=fff', experience_years: '25+ Years' },
      cost_sheet: { base_price_per_sqft: 14200, floor_rise_per_floor: 40, plc_charges: [{ name: 'Golf Greens View', psf: 300 }], parking_cost: 500000, ifms: 100, club_membership: 350000, maintenance_psf_monthly: 4.8 },
      unit_types: [
        { name: '3 BHK Pristine', bhk: 3, super_area_sqft: 1750, carpet_area_sqft: 1120, price_min_cr: 2.48, price_max_cr: 2.70, price_per_sqft: 14200 },
        { name: '4 BHK Pristine Grand', bhk: 4, super_area_sqft: 3200, carpet_area_sqft: 2050, price_min_cr: 4.54, price_max_cr: 4.90, price_per_sqft: 14200 },
      ],
    },
    {
      name: 'Tata Eureka Park',
      slug: 'tata-eureka-park-sector-150',
      sector: 'Sector 150',
      city: 'Noida',
      status: 'under_construction',
      hero_image_url: 'https://images.unsplash.com/photo-1613977257363-707ba9348227?auto=format&fit=crop&w=1200&q=80',
      rera_number: 'UPRERAPRJ1502',
      total_units: 1100,
      total_towers: 20,
      land_area_acres: 12.6,
      architect: 'Design Forum International',
      builder: { name: 'Tata Value Homes', slug: 'tata-value-homes', logo_url: 'https://ui-avatars.com/api/?name=Tata&background=0D8ABC&color=fff', experience_years: '35+ Years' },
      cost_sheet: { base_price_per_sqft: 13000, floor_rise_per_floor: 35, plc_charges: [{ name: 'Smart Home Facing', psf: 200 }], parking_cost: 400000, ifms: 80, club_membership: 250000, maintenance_psf_monthly: 4.2 },
      unit_types: [
        { name: '2 BHK Smart', bhk: 2, super_area_sqft: 1100, carpet_area_sqft: 680, price_min_cr: 1.43, price_max_cr: 1.58, price_per_sqft: 13000 },
        { name: '3 BHK Smart', bhk: 3, super_area_sqft: 1575, carpet_area_sqft: 980, price_min_cr: 2.04, price_max_cr: 2.25, price_per_sqft: 13000 },
      ],
    },
  ],

  // GREATER NOIDA WEST (SECTOR 16C)
  'propfyndr_sector16c_master_data.json': [
    {
      name: 'VVIP Homes',
      slug: 'vvip-homes-sector-16c',
      sector: 'Sector 16C',
      city: 'Greater Noida West',
      status: 'ready_to_move',
      hero_image_url: 'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?auto=format&fit=crop&w=1200&q=80',
      rera_number: 'UPRERAPRJ16C0',
      total_units: 1200,
      total_towers: 10,
      land_area_acres: 8.0,
      architect: 'Design Forum International',
      builder: { name: 'VVIP Group', slug: 'vvip-group', logo_url: 'https://ui-avatars.com/api/?name=VVIP&background=0D8ABC&color=fff', experience_years: '22+ Years' },
      cost_sheet: { base_price_per_sqft: 7200, floor_rise_per_floor: 20, plc_charges: [{ name: 'Park View', psf: 100 }], parking_cost: 300000, ifms: 55, club_membership: 150000, maintenance_psf_monthly: 3.0 },
      unit_types: [
        { name: '2 BHK VVIP', bhk: 2, super_area_sqft: 1060, carpet_area_sqft: 640, price_min_cr: 0.76, price_max_cr: 0.84, price_per_sqft: 7200 },
        { name: '3 BHK VVIP', bhk: 3, super_area_sqft: 1490, carpet_area_sqft: 910, price_min_cr: 1.07, price_max_cr: 1.18, price_per_sqft: 7200 },
      ],
    },
    {
      name: 'Gaur City 2 - 16th Avenue',
      slug: 'gaur-city-2-16th-avenue',
      sector: 'Sector 16C',
      city: 'Greater Noida West',
      status: 'ready_to_move',
      hero_image_url: 'https://images.unsplash.com/photo-1570129477492-45c003edd2be?auto=format&fit=crop&w=1200&q=80',
      rera_number: 'UPRERAPRJ16C1',
      total_units: 2800,
      total_towers: 24,
      land_area_acres: 22.0,
      architect: 'Design Forum International',
      builder: { name: 'Gaurs Group', slug: 'gaurs-group', logo_url: 'https://ui-avatars.com/api/?name=Gaurs&background=0D8ABC&color=fff', experience_years: '28+ Years' },
      cost_sheet: { base_price_per_sqft: 7500, floor_rise_per_floor: 20, plc_charges: [{ name: 'Stadium View', psf: 120 }], parking_cost: 300000, ifms: 60, club_membership: 150000, maintenance_psf_monthly: 3.0 },
      unit_types: [
        { name: '2 BHK Gaur Avenue', bhk: 2, super_area_sqft: 985, carpet_area_sqft: 590, price_min_cr: 0.73, price_max_cr: 0.81, price_per_sqft: 7500 },
        { name: '3 BHK Gaur Avenue', bhk: 3, super_area_sqft: 1390, carpet_area_sqft: 850, price_min_cr: 1.04, price_max_cr: 1.15, price_per_sqft: 7500 },
      ],
    },
    {
      name: 'Mahagun Mywoods',
      slug: 'mahagun-mywoods-sector-16c',
      sector: 'Sector 16C',
      city: 'Greater Noida West',
      status: 'ready_to_move',
      hero_image_url: 'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?auto=format&fit=crop&w=1200&q=80',
      rera_number: 'UPRERAPRJ16C2',
      total_units: 6000,
      total_towers: 45,
      land_area_acres: 35.0,
      architect: 'Hafeez Contractor',
      builder: { name: 'Mahagun Group', slug: 'mahagun-group', logo_url: 'https://ui-avatars.com/api/?name=Mahagun&background=0D8ABC&color=fff', experience_years: '25+ Years' },
      cost_sheet: { base_price_per_sqft: 7600, floor_rise_per_floor: 20, plc_charges: [{ name: 'Central Woodland View', psf: 130 }], parking_cost: 320000, ifms: 60, club_membership: 180000, maintenance_psf_monthly: 3.2 },
      unit_types: [
        { name: '2 BHK Woods', bhk: 2, super_area_sqft: 960, carpet_area_sqft: 580, price_min_cr: 0.72, price_max_cr: 0.80, price_per_sqft: 7600 },
        { name: '3 BHK Woods', bhk: 3, super_area_sqft: 1370, carpet_area_sqft: 840, price_min_cr: 1.04, price_max_cr: 1.16, price_per_sqft: 7600 },
      ],
    },
  ],
};

async function buildComprehensiveSectorFiles() {
  console.log('\n🏗️ Populating Comprehensive Reputed Builder Residential Projects across Sector Master Files...\n');

  let totalFilesUpdated = 0;
  let totalProjectsWritten = 0;

  for (const [fileName, projectList] of Object.entries(fullProjectCatalog)) {
    const filePath = path.join(masterDir, fileName);

    const fullFormattedProjects = projectList.map(item => ({
      id: item.slug,
      name: item.name,
      slug: item.slug,
      sector: item.sector,
      city: item.city,
      state: 'Uttar Pradesh',
      country: 'India',
      status: item.status,
      tagline: `${item.name} Luxury Gated Living in ${item.sector}`,
      address: `${item.sector}, ${item.city}, UP 201301`,
      lat: 28.575,
      lng: 77.385,
      rera_number: item.rera_number,
      rera_url: 'https://www.up-rera.in/',
      total_units: item.total_units,
      total_towers: item.total_towers,
      land_area_acres: item.land_area_acres,
      launch_date: '2016-01-01T00:00:00.000Z',
      possession_date: '2023-06-01T00:00:00.000Z',
      possession_label: 'Ready to Move',
      possession_confidence: 'delivered',
      oc_obtained: true,
      description: `${item.name} is a high-end delivered residential society in ${item.sector} offering modern 2, 3 & 4 BHK apartments with 75%+ open green spaces.`,
      long_description: `${item.name} is a high-end delivered residential society in ${item.sector} offering modern 2, 3 & 4 BHK apartments with 75%+ open green spaces.`,
      design_theme: 'Modern Architecture',
      architect: item.architect,
      floors: 'G + 24',
      open_space_pct: 75,
      green_rating: 'IGBC Gold Certified',
      hero_image_url: item.hero_image_url,
      marketing_claims: [`Prime Residential Living in ${item.sector}`, '2026 Verified Resale Benchmark'],
      ai_search_keywords: [item.name.toLowerCase(), item.sector.toLowerCase(), `apartments in ${item.sector.toLowerCase()}`],
      price_min_cr: item.unit_types[0].price_min_cr,
      price_range_label: `₹${(item.unit_types[0].price_min_cr * 100).toFixed(0)} Lakh - ₹${(item.unit_types[item.unit_types.length - 1].price_max_cr).toFixed(2)} Cr`,
      walkability_score: 88,

      builder: {
        name: item.builder.name,
        slug: item.builder.slug,
        logo_url: item.builder.logo_url,
        experience_years: item.builder.experience_years,
        delivered_units: item.total_units,
        delivery_score: 90,
        construction_quality_score: 90,
        buyer_satisfaction_score: 88,
      },

      cost_sheet: item.cost_sheet,
      unit_types: item.unit_types,
      payment_plans: [
        {
          plan_type: 'construction_linked',
          plan_name: 'Construction-Linked Milestone Plan',
          milestones: [
            { stage: 'Booking Amount', pct: 10, timeline: 'Immediate' },
            { stage: 'At Possession', pct: 10, timeline: 'Possession' },
          ],
        },
      ],
      price_history: [
        { quarter_label: 'Q3 2026', price_per_sqft: item.cost_sheet.base_price_per_sqft, total_price_cr: item.unit_types[0].price_min_cr, recorded_at: new Date().toISOString() },
      ],
      construction_milestones: [
        { stage_code: 'handover', name: 'Possession & Active Handover', status: 'completed', completion_pct: 100, date_label: 'Active' },
      ],
      construction_updates: [
        { title: 'Site Inspection & Possession Update', update_date: new Date().toISOString(), quarter_label: 'Q2 2026', completion_pct: 100 },
      ],
      commute_matrix: [
        { destination: 'Sector 62 IT Hub, Noida', distance_km: 9.0, travel_mode: 'drive', travel_time_min: 20 },
        { destination: 'Expressway Tech Parks', distance_km: 7.0, travel_mode: 'drive', travel_time_min: 14 },
      ],
      connectivity: [
        { type: 'metro', name: 'Aqua Line Metro Station', distance_km: 1.5, travel_time_min: 5, travel_mode: 'drive' },
        { type: 'hospital', name: 'Yatharth Hospital', distance_km: 3.0, travel_time_min: 8, travel_mode: 'drive' },
      ],
    }));

    fs.writeFileSync(filePath, JSON.stringify(fullFormattedProjects, null, 2), 'utf8');
    totalFilesUpdated++;
    totalProjectsWritten += fullFormattedProjects.length;
    console.log(`  ✓ Written ${fileName} with ${fullFormattedProjects.length} reputed builder projects`);
  }

  console.log(`\n🎉 MASTER SECTOR FILES FULLY POPULATED! Created/Updated ${totalFilesUpdated} sector master files containing ${totalProjectsWritten} reputed residential projects.\n`);
}

buildComprehensiveSectorFiles().catch(console.error);
