import Link from 'next/link'
import { ArrowLeft, Shield, Scale, FileText, AlertTriangle, Building2, UserCheck, HelpCircle, CheckCircle2, PhoneCall, MapPin } from 'lucide-react'
import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Terms of Service | RealtyPals',
  description: 'Terms of service, RERA regulatory disclosures, DPDP Act compliance, TRAI DND waivers, and platform usage guidelines for RealtyPals real estate advisory.',
}

export default function TermsOfService() {
  const lastUpdated = 'August 24, 2026'

  const sections = [
    {
      id: 'agreement',
      icon: FileText,
      title: '1. Acceptance of Terms & Intermediary Status',
      content: (
        <div className="space-y-3">
          <p>
            By accessing, browsing, or using RealtyPals (&quot;Platform&quot;, &quot;we&quot;, &quot;our&quot;, or &quot;us&quot;), including our AI-assisted advisory engine, multi-dimensional search matrix, property indices, and valuation models, you acknowledge that you have read, understood, and agree to be bound by these Terms of Service.
          </p>
          <p>
            RealtyPals operates as an analytical technology platform and digital intermediary under Section 79 of the Information Technology Act, 2000 and the Information Technology (Intermediary Guidelines and Digital Media Ethics Code) Rules, 2021, as amended. If you do not agree with any part of these terms, you must immediately discontinue use of the platform.
          </p>
        </div>
      ),
    },
    {
      id: 'advisory-disclaimer',
      icon: AlertTriangle,
      title: '2. AI Real Estate Advisory & Analytical Disclaimer',
      badge: 'Critical Notice',
      content: (
        <div className="space-y-3">
          <p className="font-medium text-slate-900 dark:text-slate-100">
            RealtyPals provides AI-powered real estate intelligence, historical market trajectory analysis, and comparative project evaluations strictly for informational, educational, and preliminary research purposes.
          </p>
          <ul className="list-disc list-inside space-y-2 ml-2 text-slate-600 dark:text-slate-400">
            <li>
              <strong>Not Financial, Legal, or Certified Investment Advice:</strong> Recommendations, calculations (including estimated EMIs, tax offsets, spatial efficiency scores, or capital appreciation projections) generated by our platform do not constitute certified financial, legal, taxation, or certified investment advisory under SEBI or ICAI guidelines.
            </li>
            <li>
              <strong>Mandatory Independent Due Diligence:</strong> Property buyers and investors are strongly advised to independently verify all developer claims, encumbrance certificates, approved building sanctions, land title deeds, and environmental clearances through certified legal and technical counsel before executing agreements or making monetary commitments.
            </li>
          </ul>
        </div>
      ),
    },
    {
      id: 'rera-compliance',
      icon: Shield,
      title: '3. UP-RERA & Channel Partner Disclosures',
      badge: 'UP-RERA Aligned',
      content: (
        <div className="space-y-3">
          <p>
            RealtyPals indexes and evaluates residential projects registered under the Real Estate (Regulation and Development) Act, 2016 (RERA) and registered with the Uttar Pradesh Real Estate Regulatory Authority (UP-RERA) for Noida, Greater Noida, and Yamuna Expressway micro-markets.
          </p>
          <ul className="list-disc list-inside space-y-2 ml-2 text-slate-600 dark:text-slate-400">
            <li>
              <strong>Verified Public RERA Identifiers:</strong> Project RERA registration numbers and promoter details displayed across project cards, decision matrices, and detail drawers are referenced directly from public UP-RERA disclosures. Users are encouraged to cross-verify all statutory filings on the official government portal (<a href="https://up-rera.in" target="_blank" rel="noopener noreferrer" className="text-blue-600 dark:text-blue-400 hover:underline font-semibold">up-rera.in</a>).
            </li>
            <li>
              <strong>Channel Partner &amp; Lead Fulfillment Routing:</strong> When a user requests a site visit, developer callback, or project cost sheet, lead coordination and site inspections may be facilitated directly by the respective UP-RERA registered developer or their authorized, UP-RERA registered Channel Partner (Real Estate Agent).
            </li>
            <li>
              <strong>Technology Aggregator Status:</strong> RealtyPals functions strictly as an analytical intelligence layer. We do not solicit investments, underwrite developments, or act as an escrow agent.
            </li>
          </ul>
        </div>
      ),
    },
    {
      id: 'lead-consent-trai',
      icon: PhoneCall,
      title: '4. Lead Consent, Communications & TRAI / DND Waiver',
      badge: 'TRAI TCCR Compliant',
      content: (
        <div className="space-y-3">
          <p>
            By submitting your contact details (including phone number, email address, or scheduling preference) on RealtyPals for a project inquiry, brochure download, price sheet request, or site inspection:
          </p>
          <ul className="list-disc list-inside space-y-2 ml-2 text-slate-600 dark:text-slate-400">
            <li>
              <strong>Express Communication Authorization:</strong> You explicitly authorize RealtyPals, the concerned UP-RERA registered developers, and their authorized channel partners to contact you via Phone Calls, SMS, WhatsApp messages, and Electronic Mail regarding property updates, inventory availability, and scheduling details.
            </li>
            <li>
              <strong>TRAI / National DND Registry Waiver:</strong> You expressly agree that this request constitutes an unsolicited commercial communications exemption under the Telecom Commercial Communications Customer Preference Regulations, 2018 (TRAI TCCR). This consent explicitly overrides any existing registration on the National Do Not Call (NDNC / DND) Registry or Telecom Service Provider preference registers for a period of 12 months or until explicit written consent revocation.
            </li>
            <li>
              <strong>Consent Revocation:</strong> You may withdraw your communication consent at any time by emailing <a href="mailto:privacy@realtypals.in" className="text-blue-600 dark:text-blue-400 hover:underline font-semibold">privacy@realtypals.in</a> with your registered phone number.
            </li>
          </ul>
        </div>
      ),
    },
    {
      id: 'platform-use',
      icon: UserCheck,
      title: '5. Permitted Use & User Obligations',
      content: (
        <div className="space-y-3">
          <p>As a condition of your use of the Platform, you agree to:</p>
          <ul className="list-disc list-inside space-y-2 ml-2 text-slate-600 dark:text-slate-400">
            <li>Provide authentic, accurate, and current contact details when scheduling site visits, requesting developer callbacks, or saving property shortlists.</li>
            <li>Not scrape, crawl, reverse engineer, or programmatically query our conversational AI engine, verified database, or pricing indices without prior explicit written consent.</li>
            <li>Not misrepresent your identity or attempt to gain unauthorized administrative access to our systems, APIs, or developer consoles.</li>
          </ul>
        </div>
      ),
    },
    {
      id: 'builder-relationships',
      icon: Building2,
      title: '6. Builder Specifications & Timeline Variations',
      content: (
        <div className="space-y-3">
          <p>
            Floor plans, master layouts, 3D renderings, specifications, construction milestones, and possession timelines are gathered from developer brochures, official RERA quarterly progress reports (QPRs), and verified site audits. While we apply continuous validation pipelines:
          </p>
          <ul className="list-disc list-inside space-y-2 ml-2 text-slate-600 dark:text-slate-400">
            <li>Developers reserve the statutory right to modify unit layouts, finishings, and payment milestone structures subject to applicable RERA approvals and buyer consent rules.</li>
            <li>RealtyPals is not liable for project completion delays, deviation in promised amenities, force majeure disruptions, or contractual disputes between buyers and builders.</li>
          </ul>
        </div>
      ),
    },
    {
      id: 'limitation-liability',
      icon: Scale,
      title: '7. Limitation of Liability',
      content: (
        <div className="space-y-3">
          <p>
            To the maximum extent permitted by applicable Indian law (including the Consumer Protection Act, 2019 and relevant e-commerce guidelines), RealtyPals, its directors, officers, employees, and technology partners shall not be liable for any indirect, incidental, special, consequential, or punitive damages, including loss of profits, property valuation differences, or business interruption arising from your access to or reliance upon platform insights.
          </p>
        </div>
      ),
    },
    {
      id: 'governing-law',
      icon: CheckCircle2,
      title: '8. Governing Law & Dispute Resolution',
      content: (
        <div className="space-y-3">
          <p>
            These Terms shall be governed by, construed, and enforced in accordance with the laws of the Republic of India. Any legal action, dispute, or proceeding arising out of or related to the Platform shall be subject to the exclusive jurisdiction of the competent courts located in <strong>Gautam Buddh Nagar (Noida), Uttar Pradesh, India</strong>.
          </p>
        </div>
      ),
    },
  ]

  return (
    <div className="min-h-screen bg-[#F8FAFC] dark:bg-[#090D16] text-slate-800 dark:text-slate-200 transition-colors">
      {/* Header Banner */}
      <header className="border-b border-slate-200/80 dark:border-slate-800/80 bg-white/70 dark:bg-slate-900/70 backdrop-blur-md sticky top-0 z-20">
        <div className="max-w-5xl mx-auto px-4 sm:px-6 lg:px-8 py-4 flex items-center justify-between">
          <Link
            href="/"
            className="inline-flex items-center gap-2 text-sm font-semibold text-slate-600 dark:text-slate-300 hover:text-blue-600 dark:hover:text-blue-400 transition-colors"
          >
            <ArrowLeft size={16} />
            <span>Back to Home</span>
          </Link>
          <div className="text-xs font-semibold text-slate-500 dark:text-slate-400 bg-slate-100 dark:bg-slate-800 px-3 py-1 rounded-full">
            Last Updated: {lastUpdated}
          </div>
        </div>
      </header>

      <main className="max-w-5xl mx-auto px-4 sm:px-6 lg:px-8 py-12">
        {/* Title Hero */}
        <div className="mb-10 text-center sm:text-left">
          <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full text-xs font-bold uppercase tracking-wider text-blue-700 dark:text-blue-300 bg-blue-50 dark:bg-blue-950/60 border border-blue-200/60 dark:border-blue-800/60 mb-4">
            <Scale size={13} /> Legal &amp; Regulatory Governance
          </div>
          <h1 className="text-3xl sm:text-4xl font-extrabold text-slate-900 dark:text-white tracking-tight">
            Terms of Service
          </h1>
          <p className="mt-3 text-base text-slate-600 dark:text-slate-400 max-w-3xl leading-relaxed">
            Please read these terms carefully before utilizing RealtyPals. They outline the regulatory status of our AI advisory tools, RERA compliance standards, lead routing terms, and mutual responsibilities.
          </p>
        </div>

        {/* Highlight Callout */}
        <div className="mb-10 p-5 rounded-2xl bg-gradient-to-r from-blue-50 to-indigo-50 dark:from-blue-950/40 dark:to-indigo-950/40 border border-blue-200/80 dark:border-blue-800/60 flex flex-col sm:flex-row items-start sm:items-center gap-4">
          <div className="w-10 h-10 rounded-xl bg-blue-600 text-white flex items-center justify-center flex-shrink-0 shadow-md">
            <Shield size={20} />
          </div>
          <div className="flex-1">
            <h2 className="text-sm font-bold text-blue-900 dark:text-blue-200">
              RERA Compliant &amp; Independent Real Estate Intelligence
            </h2>
            <p className="text-xs sm:text-sm text-blue-800/80 dark:text-blue-300/80 mt-0.5">
              RealtyPals indexes verified public UP-RERA records for Noida &amp; Greater Noida. We maintain strict analytical neutrality and transparent statutory compliance.
            </p>
          </div>
        </div>

        {/* Section Cards */}
        <div className="space-y-6">
          {sections.map((section) => {
            const Icon = section.icon
            return (
              <section
                key={section.id}
                id={section.id}
                className="p-6 sm:p-7 rounded-2xl bg-white dark:bg-slate-900 border border-slate-200/80 dark:border-slate-800 shadow-sm transition-shadow hover:shadow-md"
              >
                <div className="flex items-center justify-between gap-3 mb-4">
                  <div className="flex items-center gap-3">
                    <div className="w-8 h-8 rounded-lg bg-slate-100 dark:bg-slate-800 text-blue-600 dark:text-blue-400 flex items-center justify-center">
                      <Icon size={18} />
                    </div>
                    <h2 className="text-lg sm:text-xl font-bold text-slate-900 dark:text-white">
                      {section.title}
                    </h2>
                  </div>
                  {section.badge && (
                    <span className="text-[11px] font-bold uppercase tracking-wider px-2.5 py-0.5 rounded-md bg-amber-100 dark:bg-amber-950/60 text-amber-800 dark:text-amber-300 border border-amber-200/80 dark:border-amber-800/60">
                      {section.badge}
                    </span>
                  )}
                </div>
                <div className="text-sm text-slate-700 dark:text-slate-300 leading-relaxed">
                  {section.content}
                </div>
              </section>
            )
          })}
        </div>

        {/* Statutory Grievance Redressal Card (Mandatory in India) */}
        <div className="mt-10 p-6 sm:p-7 rounded-2xl bg-white dark:bg-slate-900 border border-slate-200/80 dark:border-slate-800 shadow-sm">
          <div className="flex items-center gap-3 mb-4">
            <div className="w-8 h-8 rounded-lg bg-blue-50 dark:bg-blue-950/60 text-blue-600 dark:text-blue-400 flex items-center justify-center">
              <HelpCircle size={18} />
            </div>
            <div>
              <h2 className="text-lg font-bold text-slate-900 dark:text-white">
                Statutory Grievance Redressal Mechanism
              </h2>
              <p className="text-xs text-slate-500 dark:text-slate-400">
                In compliance with the Information Technology Act, 2000 and DPDP Act, 2023
              </p>
            </div>
          </div>
          
          <div className="grid sm:grid-cols-2 gap-4 text-xs text-slate-600 dark:text-slate-400 pt-2 border-t border-slate-100 dark:border-slate-800">
            <div>
              <span className="font-semibold text-slate-900 dark:text-white block mb-1">Grievance &amp; Compliance Officer:</span>
              <p>Legal &amp; Regulatory Cell</p>
              <p>RealtyPals Technologies Private Limited</p>
              <p className="mt-1 flex items-center gap-1.5 text-slate-700 dark:text-slate-300">
                <MapPin size={13} className="text-blue-500 shrink-0" />
                Sector 62, Noida, Gautam Buddh Nagar, UP 201301, India
              </p>
            </div>
            <div>
              <span className="font-semibold text-slate-900 dark:text-white block mb-1">Resolution SLA &amp; Contact:</span>
              <p>Official Email: <a href="mailto:grievance@realtypals.in" className="text-blue-600 dark:text-blue-400 hover:underline font-semibold">grievance@realtypals.in</a></p>
              <p>General Legal: <a href="mailto:legal@realtypals.in" className="text-blue-600 dark:text-blue-400 hover:underline font-semibold">legal@realtypals.in</a></p>
              <p className="mt-1 text-[11px] text-emerald-600 dark:text-emerald-400 font-medium">
                ✓ Acknowledgment within 48 hours · Redressal within 15 days
              </p>
            </div>
          </div>
        </div>
      </main>
    </div>
  )
}
