'use client'

import { useRef, useEffect } from 'react'
import { motion, AnimatePresence } from 'framer-motion'
import type { ChipAction } from './types'

interface ChipPickerProps {
  chips: ChipAction[]
  onAction: (chip: ChipAction) => void
  className?: string
  /** If true, show as an inline horizontal scroll row; default is horizontal scroll */
  variant?: 'inline' | 'wrap'
}

/**
 * ChipPicker — Renders contextual conversation suggestion chips.
 *
 * Chips are generated by the backend `ui_state` engine and evolve per conversation stage:
 * DISCOVERY   → starter chips (budget, type, features)
 * CLARIFYING  → intent-filling chips (BHK, sector, budget range)
 * RESEARCH    → deep-dive + workflow chips (compare, shortlist, price history)
 * DECIDING    → action chips (EMI calc, book visit, share)
 * CONVERTING  → workflow chips (book, callback, save)
 */
export default function ChipPicker({ chips, onAction, className = '', variant = 'inline' }: ChipPickerProps) {
  const scrollRef = useRef<HTMLDivElement>(null)

  // Sort chips by priority (lower number = higher priority)
  const sorted = [...chips].sort((a, b) => a.priority - b.priority)

  if (!sorted.length) return null

  return (
    <AnimatePresence mode="wait">
      <motion.div
        key={sorted.map(c => c.id).join(',')}
        initial={{ opacity: 0, y: 6 }}
        animate={{ opacity: 1, y: 0 }}
        exit={{ opacity: 0, y: -4 }}
        transition={{ duration: 0.2, ease: 'easeOut' }}
        className={`w-full ${className}`}
      >
        <div
          ref={scrollRef}
          className={
            variant === 'wrap'
              ? 'flex flex-wrap gap-2'
              : 'flex gap-2 overflow-x-auto scrollbar-hide pb-0.5'
          }
          style={variant === 'inline' ? { WebkitOverflowScrolling: 'touch' } : undefined}
        >
          {sorted.map((chip) => (
            <ChipButton key={chip.id} chip={chip} onAction={onAction} />
          ))}
        </div>
      </motion.div>
    </AnimatePresence>
  )
}

function ChipButton({ chip, onAction }: { chip: ChipAction; onAction: (chip: ChipAction) => void }) {
  // Style varies by action type
  const isAction = chip.actionType === 'BOOK_VISIT' || chip.actionType === 'CALCULATE_EMI' || chip.actionType === 'COMPARE_PROPERTIES'
  const isClarification = chip.actionType === 'INTENT_PATCH'

  const baseClass = 'flex-shrink-0 inline-flex items-center gap-1.5 px-3.5 py-1.5 rounded-full text-[12.5px] font-medium transition-all duration-200 cursor-pointer active:scale-[0.97] whitespace-nowrap select-none'

  const styleClass = isAction
    ? 'bg-[#3061F2]/10 dark:bg-[#3061F2]/15 text-[#3061F2] dark:text-blue-400 border border-[#3061F2]/20 dark:border-blue-500/20 hover:bg-[#3061F2]/15 dark:hover:bg-[#3061F2]/25 hover:border-[#3061F2]/30'
    : isClarification
    ? 'bg-amber-50 dark:bg-amber-900/20 text-amber-700 dark:text-amber-300 border border-amber-200 dark:border-amber-700/40 hover:bg-amber-100 dark:hover:bg-amber-900/30'
    : 'bg-white dark:bg-white/6 text-gray-700 dark:text-gray-300 border border-gray-200/70 dark:border-white/10 hover:bg-gray-50 dark:hover:bg-white/10 hover:border-gray-300 dark:hover:border-white/15 shadow-[0_1px_3px_rgba(0,0,0,0.04)]'

  return (
    <button
      onClick={() => onAction(chip)}
      className={`${baseClass} ${styleClass}`}
      title={chip.label}
    >
      {chip.icon && <span className="text-[14px] leading-none">{chip.icon}</span>}
      <span>{chip.label}</span>
    </button>
  )
}
