// ─── Conversation Action Types ────────────────────────────────────────────────
// Every user interaction is a ConversationAction. TEXT_MESSAGE runs LLM
// extraction. INTENT_PATCH skips LLM — backend merges the patch directly.

export type ConversationActionType =
  | 'TEXT_MESSAGE'        // natural language → extractIntent → full pipeline
  | 'INTENT_PATCH'        // deterministic UI selection → skip extractIntent
  | 'COMPARE_PROPERTIES'  // opens compare workflow
  | 'CALCULATE_EMI'       // opens EMI calculator
  | 'BOOK_VISIT'          // opens site visit scheduler
  | 'REMOVE_FILTER'       // removes an intent field (from Context Ribbon)
  | 'OPEN_TOOL'           // opens a UI panel without a network call

// Payload shapes per action type
export interface TextMessagePayload { text: string }
export interface IntentPatchPayload { patch: Record<string, unknown>; label: string }
export interface ComparePayload { slugs: string[]; label?: string }
export interface RemoveFilterPayload { field: keyof IntentPatchPayload['patch'] }
export interface OpenToolPayload { tool: 'calculator' | 'map' | 'share' | 'site_visit'; projectSlug?: string }

export interface ConversationAction {
  type: ConversationActionType
  payload: Record<string, unknown>
}

// ─── Chip Action ──────────────────────────────────────────────────────────────
// Every button/chip in the UI is a ChipAction. Generated by the backend engine.

// Optional grouping metadata — the engine decides how many groups exist and
// how many chips belong to each. The frontend only renders what it's given,
// in the order given; it has no opinion on group counts or sizes.
export interface ChipGroup {
  id:       string
  label:    string
  order:    number
  emphasis: 'primary' | 'secondary' | 'tertiary'
}

export interface ChipAction {
  id: string                    // stable unique ID — used to prevent duplicate renders
  actionType: ConversationActionType
  label: string
  icon: string                  // emoji
  analyticsId: string
  priority: number              // 1 = highest; chips sorted by priority
  payload: Record<string, unknown>
  group?: ChipGroup
}

// ─── Conversation Stage ───────────────────────────────────────────────────────
// Deterministic stage computed by the backend Conversation Engine.

export type ConversationStage =
  | 'DISCOVERY'    // no intent signals; show starter chips
  | 'CLARIFYING'   // 1 signal present; ask for missing fields
  | 'SEARCHING'    // intent is READY_TO_SEARCH; DB query running
  | 'RESEARCH'     // results visible; user exploring options
  | 'COMPARING'    // comparison table active
  | 'DECIDING'     // shortlist narrowed to 1–2 projects
  | 'CONVERTING'   // lead capture: visit/callback/save

// ─── Conversation State ───────────────────────────────────────────────────────
// Canonical frontend state derived from the backend `ui_state` SSE event.

export interface ConversationState {
  stage: ConversationStage
  thinking: string              // displayed in the thinking loader
  chips: ChipAction[]           // progressive suggestions — max 5, unless grouped
  missingFields: string[]       // ['sector', 'budget'] — drives Context Ribbon
  confidence: 'HIGH' | 'MEDIUM' | 'LOW'
}

// ─── Legacy types (kept during migration) ────────────────────────────────────

export type ChipPickerMode = 'single' | 'multi'


export interface ChipPickerState {
  mode: ChipPickerMode
  action: string
  label: string
  isModal: boolean
  selected: string[]
}
