-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.builders (
  id text NOT NULL,
  name text NOT NULL,
  slug text NOT NULL,
  tagline text,
  parent_group text,
  founded_year integer,
  headquarters text,
  website text,
  email text,
  phone text,
  credai_member boolean NOT NULL DEFAULT false,
  delivered_units integer,
  delivered_projects ARRAY,
  ongoing_projects ARRAY,
  awards ARRAY,
  awards_count integer,
  description text,
  created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  affordable_specialization boolean NOT NULL DEFAULT false,
  after_sales_score integer,
  audit_flags_log text,
  average_delay_months double precision,
  average_project_size integer,
  buyer_satisfaction_score integer,
  certifications ARRAY,
  cin text,
  company_overview text,
  construction_quality_score integer,
  data_source text,
  delayed_projects_count integer,
  delivery_score integer,
  executives jsonb,
  experience_years text,
  financial_hygiene_score integer,
  founder text,
  funding_banks ARRAY,
  insolvency_history boolean NOT NULL DEFAULT false,
  intelligence_completeness integer,
  iso_certified boolean NOT NULL DEFAULT false,
  last_verified_at timestamp without time zone,
  legal_entities jsonb,
  legal_flag text,
  litigation_count integer,
  logo_url text,
  luxury_specialization boolean NOT NULL DEFAULT false,
  outstanding_dues_cr double precision,
  projects_delivered_count integer DEFAULT 18,
  rera_compliance_score integer,
  rera_promoter_id text,
  total_projects_count integer,
  township_specialization boolean NOT NULL DEFAULT false,
  verification_level text,
  CONSTRAINT builders_pkey PRIMARY KEY (id)
);
CREATE TABLE public.projects (
  id text NOT NULL,
  slug text NOT NULL,
  name text NOT NULL,
  tagline text,
  builder_id text NOT NULL,
  rera_number text,
  rera_url text,
  city text NOT NULL DEFAULT 'Noida'::text,
  sector text NOT NULL,
  address text,
  lat double precision,
  lng double precision,
  land_area_acres double precision,
  total_units integer,
  total_towers integer,
  status USER-DEFINED NOT NULL,
  possession_date timestamp without time zone,
  possession_label text,
  description text,
  long_description text,
  design_theme text,
  architect text,
  interior_designer text,
  marketing_claims ARRAY,
  ai_search_keywords ARRAY,
  hero_image_url text,
  created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp without time zone NOT NULL,
  banks_nearby_count integer,
  builder_theme jsonb,
  embedding USER-DEFINED,
  escrow_bank_name text,
  escrow_verified boolean,
  floors text,
  green_rating text,
  has_duplex boolean NOT NULL DEFAULT false,
  has_penthouse boolean NOT NULL DEFAULT false,
  hospitals_nearby_count integer,
  it_parks_nearby_count integer,
  launch_date timestamp without time zone,
  nclt_moratorium_active boolean,
  open_space_pct integer,
  price_min_cr double precision,
  price_range_label text,
  project_risk_flag text,
  project_type text DEFAULT 'Residential'::text,
  registry_embargo_reasons ARRAY,
  registry_status text,
  restaurants_nearby_count integer,
  schools_nearby_count integer,
  shopping_nearby_count integer,
  country text NOT NULL DEFAULT 'India'::text,
  state text NOT NULL DEFAULT 'Uttar Pradesh'::text,
  aqi_annual_avg double precision,
  commute_matrix jsonb,
  flood_waterlogging_risk text,
  legal_flag text,
  legal_flag_detail text,
  litigation_count integer,
  location_advantages jsonb,
  location_concerns ARRAY,
  location_verdict text,
  oc_obtained boolean,
  oc_obtained_date timestamp without time zone,
  oc_restrictions text,
  oc_valid_until text,
  possession_confidence text,
  possession_confidence_note text,
  rera_compliance_score integer,
  rera_valid_until timestamp without time zone,
  walkability_score integer,
  CONSTRAINT projects_pkey PRIMARY KEY (id),
  CONSTRAINT projects_builder_id_fkey FOREIGN KEY (builder_id) REFERENCES public.builders(id)
);
CREATE TABLE public.unit_types (
  id text NOT NULL,
  project_id text NOT NULL,
  name text NOT NULL,
  bhk integer NOT NULL,
  super_area_sqft integer,
  carpet_area_sqft integer,
  balcony_area_sqft integer,
  bathrooms integer,
  utility_room boolean NOT NULL DEFAULT false,
  dress_area boolean NOT NULL DEFAULT false,
  towers ARRAY,
  price_min_cr double precision,
  price_max_cr double precision,
  price_label text,
  price_is_estimated boolean NOT NULL DEFAULT true,
  category_badge text,
  description text,
  inventory_left integer,
  key_highlights jsonb,
  perfect_for ARRAY,
  subtitle text,
  views jsonb,
  whats_included jsonb,
  balconies integer,
  carpet_to_super_ratio_pct double precision,
  has_servant_room boolean NOT NULL DEFAULT false,
  has_study boolean NOT NULL DEFAULT false,
  inventory_as_of timestamp without time zone,
  layout_cons ARRAY,
  layout_efficiency_pct double precision,
  layout_pros ARRAY,
  layout_shape text,
  orientation_price_premium_pct double precision,
  price_per_sqft double precision,
  super_area_range_sqft text,
  unit_orientations ARRAY,
  CONSTRAINT unit_types_pkey PRIMARY KEY (id),
  CONSTRAINT unit_types_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.projects(id)
);
CREATE TABLE public.project_images (
  id text NOT NULL,
  project_id text NOT NULL,
  url text NOT NULL,
  type USER-DEFINED NOT NULL,
  caption text,
  sort_order integer NOT NULL DEFAULT 0,
  bhk integer,
  size_sqft integer,
  source text NOT NULL DEFAULT 'admin'::text,
  CONSTRAINT project_images_pkey PRIMARY KEY (id),
  CONSTRAINT project_images_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.projects(id)
);
CREATE TABLE public.amenities (
  id text NOT NULL,
  project_id text NOT NULL,
  name text NOT NULL,
  category USER-DEFINED NOT NULL,
  CONSTRAINT amenities_pkey PRIMARY KEY (id),
  CONSTRAINT amenities_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.projects(id)
);
CREATE TABLE public.connectivity (
  id text NOT NULL,
  project_id text NOT NULL,
  type USER-DEFINED NOT NULL,
  name text NOT NULL,
  distance_km double precision,
  data_source USER-DEFINED NOT NULL DEFAULT 'brochure'::"DataSource",
  notes text,
  category_rank integer,
  extra_detail text,
  is_operational boolean NOT NULL DEFAULT true,
  peak_travel_time_min integer,
  rating double precision,
  travel_mode text,
  travel_time_min integer,
  CONSTRAINT connectivity_pkey PRIMARY KEY (id),
  CONSTRAINT connectivity_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.projects(id)
);
CREATE TABLE public.chat_sessions (
  id text NOT NULL,
  user_id text,
  guest_token text,
  title text,
  message_count integer NOT NULL DEFAULT 0,
  created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  last_active timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  chat_phase text NOT NULL DEFAULT 'DISCOVERY'::text,
  last_projects jsonb,
  shown_chip_ids jsonb DEFAULT '[]'::jsonb,
  summary text,
  focus_project_id text,
  focus_set_at timestamp without time zone,
  property_reactions jsonb DEFAULT '[]'::jsonb,
  summary_financial text,
  summary_location text,
  summary_timeline text,
  CONSTRAINT chat_sessions_pkey PRIMARY KEY (id)
);
CREATE TABLE public.chat_messages (
  id text NOT NULL,
  session_id text NOT NULL,
  role USER-DEFINED NOT NULL,
  content text NOT NULL,
  intent_snapshot jsonb,
  created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  artifacts jsonb,
  chips jsonb DEFAULT '[]'::jsonb,
  CONSTRAINT chat_messages_pkey PRIMARY KEY (id),
  CONSTRAINT chat_messages_session_id_fkey FOREIGN KEY (session_id) REFERENCES public.chat_sessions(id)
);
CREATE TABLE public.user_memory (
  id text NOT NULL,
  user_id text,
  bhk_preference integer,
  budget_min_cr double precision,
  budget_max_cr double precision,
  sector_preference text,
  purpose text,
  possession_pref text,
  viewed_slugs ARRAY,
  rejected_slugs ARRAY,
  saved_slugs ARRAY,
  summary_text text,
  updated_at timestamp without time zone NOT NULL,
  work_location text,
  home_loan_pre_approved boolean,
  timeline_months integer,
  contact_phone text,
  guest_token text,
  CONSTRAINT user_memory_pkey PRIMARY KEY (id)
);
CREATE TABLE public.saved_properties (
  id text NOT NULL,
  user_id text NOT NULL,
  project_id text NOT NULL,
  saved_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT saved_properties_pkey PRIMARY KEY (id),
  CONSTRAINT saved_properties_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.projects(id)
);
CREATE TABLE public.site_visit_requests (
  id text NOT NULL,
  project_id text NOT NULL,
  project_slug text NOT NULL,
  project_name text NOT NULL,
  name text NOT NULL,
  phone text NOT NULL,
  email text,
  visit_date timestamp without time zone NOT NULL,
  time_slot text NOT NULL,
  message text,
  created_at timestamp without time zone NOT NULL DEFAULT now(),
  status USER-DEFINED NOT NULL DEFAULT 'pending'::"SiteVisitStatus",
  CONSTRAINT site_visit_requests_pkey PRIMARY KEY (id)
);
CREATE TABLE public.price_alerts (
  id text NOT NULL,
  user_id text,
  guest_token text,
  project_id text NOT NULL,
  project_slug text NOT NULL,
  target_price_cr double precision NOT NULL,
  notified boolean NOT NULL DEFAULT false,
  created_at timestamp without time zone NOT NULL DEFAULT now(),
  CONSTRAINT price_alerts_pkey PRIMARY KEY (id)
);
CREATE TABLE public.project_documents (
  id text NOT NULL,
  project_id text NOT NULL,
  project_slug text NOT NULL,
  name text NOT NULL,
  storage_url text NOT NULL,
  content_text text,
  doc_type text NOT NULL DEFAULT 'brochure'::text,
  created_at timestamp without time zone NOT NULL DEFAULT now(),
  file_size_bytes integer,
  CONSTRAINT project_documents_pkey PRIMARY KEY (id)
);
CREATE TABLE public._prisma_migrations (
  id character varying NOT NULL,
  checksum character varying NOT NULL,
  finished_at timestamp with time zone,
  migration_name character varying NOT NULL,
  logs text,
  rolled_back_at timestamp with time zone,
  started_at timestamp with time zone NOT NULL DEFAULT now(),
  applied_steps_count integer NOT NULL DEFAULT 0,
  CONSTRAINT _prisma_migrations_pkey PRIMARY KEY (id)
);
CREATE TABLE public.chat_analytics (
  id text NOT NULL,
  session_id text NOT NULL,
  promotional_id text,
  promo_clicked boolean NOT NULL DEFAULT false,
  created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ai_confidence integer,
  latency_ms integer,
  llm_tokens integer,
  chat_started_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  conversion_at timestamp without time zone,
  conversion_type text,
  converted_builder_id text,
  converted_project_id text,
  drop_off_at timestamp without time zone,
  drop_off_stage text,
  extracted_bhk integer,
  extracted_budget_max double precision,
  extracted_budget_min double precision,
  extracted_sector text,
  first_engagement_at timestamp without time zone,
  guest_token text,
  idle_seconds_before_drop_off integer,
  intent_identified_at timestamp without time zone,
  intent_type text,
  projects_clicked integer NOT NULL DEFAULT 0,
  projects_saved integer NOT NULL DEFAULT 0,
  projects_viewed integer NOT NULL DEFAULT 0,
  results_shown_at timestamp without time zone,
  time_spent_seconds integer NOT NULL DEFAULT 0,
  user_id text,
  CONSTRAINT chat_analytics_pkey PRIMARY KEY (id),
  CONSTRAINT chat_analytics_session_id_fkey FOREIGN KEY (session_id) REFERENCES public.chat_sessions(id)
);
CREATE TABLE public.query_metrics (
  id text NOT NULL,
  session_id text NOT NULL,
  clicked boolean NOT NULL DEFAULT false,
  converted boolean NOT NULL DEFAULT false,
  created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  builder text,
  clarification_count integer NOT NULL DEFAULT 0,
  had_results boolean,
  possession text,
  purpose text,
  results_count integer,
  bhk integer,
  budget_max_cr double precision,
  budget_min_cr double precision,
  intent_type text,
  query_text text NOT NULL DEFAULT ''::text,
  sector text,
  user_id text,
  week_start timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT query_metrics_pkey PRIMARY KEY (id),
  CONSTRAINT query_metrics_session_id_fkey FOREIGN KEY (session_id) REFERENCES public.chat_sessions(id)
);
CREATE TABLE public.property_events (
  id text NOT NULL,
  session_id text NOT NULL,
  user_id text,
  guest_token text,
  project_id text NOT NULL,
  action text NOT NULL,
  created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT property_events_pkey PRIMARY KEY (id),
  CONSTRAINT property_events_session_id_fkey FOREIGN KEY (session_id) REFERENCES public.chat_sessions(id)
);
CREATE TABLE public.project_dna (
  id text NOT NULL,
  project_id text NOT NULL,
  last_verified_at timestamp without time zone,
  verified_by text,
  created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp without time zone NOT NULL,
  overall_score integer,
  builder_score integer,
  price_score integer,
  location_score integer,
  legal_score integer,
  amenity_score integer,
  possession_score integer,
  CONSTRAINT project_dna_pkey PRIMARY KEY (id),
  CONSTRAINT project_dna_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.projects(id)
);
CREATE TABLE public.decision_profiles (
  id text NOT NULL,
  project_id text NOT NULL,
  status USER-DEFINED NOT NULL DEFAULT 'DRAFT'::"IntelligenceStatus",
  decision_thesis text,
  why_buy ARRAY DEFAULT ARRAY[]::text[],
  why_avoid ARRAY DEFAULT ARRAY[]::text[],
  best_for text,
  not_ideal_for text,
  confidence_sources ARRAY DEFAULT ARRAY[]::text[],
  recommendation_notes text,
  advisor_notes text,
  last_verified_at timestamp without time zone,
  verified_by text,
  created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp without time zone NOT NULL,
  financial_intelligence jsonb,
  market_intelligence jsonb,
  builder_intelligence jsonb,
  property_intelligence jsonb,
  comparative_analysis jsonb,
  resources_documents jsonb,
  CONSTRAINT decision_profiles_pkey PRIMARY KEY (id),
  CONSTRAINT decision_profiles_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.projects(id)
);
CREATE TABLE public.persona_profiles (
  id text NOT NULL,
  project_id text NOT NULL,
  primary_persona text,
  secondary_personas ARRAY DEFAULT ARRAY[]::text[],
  persona_descriptions jsonb,
  income_range text,
  family_stage text,
  work_location text,
  risk_appetite text,
  timeline_horizon text,
  motivation_note text,
  last_verified_at timestamp without time zone,
  verified_by text,
  created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp without time zone NOT NULL,
  CONSTRAINT persona_profiles_pkey PRIMARY KEY (id),
  CONSTRAINT persona_profiles_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.projects(id)
);
CREATE TABLE public.recommendation_profiles (
  id text NOT NULL,
  project_id text NOT NULL,
  status USER-DEFINED NOT NULL DEFAULT 'DRAFT'::"IntelligenceStatus",
  tier text,
  primary_thesis text,
  walk_away_conditions ARRAY DEFAULT ARRAY[]::text[],
  timeline_advice text,
  negotiation_leverage ARRAY DEFAULT ARRAY[]::text[],
  internal_confidence text,
  admin_notes text,
  last_verified_at timestamp without time zone,
  verified_by text,
  created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp without time zone NOT NULL,
  CONSTRAINT recommendation_profiles_pkey PRIMARY KEY (id),
  CONSTRAINT recommendation_profiles_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.projects(id)
);
CREATE TABLE public.project_competitors (
  id text NOT NULL,
  project_id text NOT NULL,
  competitor_project_id text,
  competitor_name text NOT NULL,
  competitor_slug text,
  this_project_advantage text,
  competitor_advantage text,
  verdict text,
  price_delta_note text,
  sort_order integer NOT NULL DEFAULT 0,
  last_verified_at timestamp without time zone,
  verified_by text,
  created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp without time zone NOT NULL,
  competitor_amenity_count integer,
  competitor_possession_status text,
  competitor_price_max_cr double precision,
  competitor_price_min_cr double precision,
  competitor_price_psf double precision,
  reason text,
  CONSTRAINT project_competitors_pkey PRIMARY KEY (id),
  CONSTRAINT project_competitors_competitor_project_id_fkey FOREIGN KEY (competitor_project_id) REFERENCES public.projects(id),
  CONSTRAINT project_competitors_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.projects(id)
);
CREATE TABLE public.intelligence_audits (
  id text NOT NULL,
  project_id text NOT NULL,
  section text NOT NULL,
  action text NOT NULL,
  before_data jsonb,
  after_data jsonb,
  created_by text,
  created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT intelligence_audits_pkey PRIMARY KEY (id)
);
CREATE TABLE public.callback_requests (
  id text NOT NULL,
  name text NOT NULL,
  phone text NOT NULL,
  project_name text,
  project_slug text,
  user_id text,
  guest_token text,
  status text NOT NULL DEFAULT 'new'::text,
  created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  lead_score double precision,
  lead_tier text,
  intent_tier text,
  loan_pre_approved boolean,
  ai_summary text,
  consent_given boolean,
  projects_saved integer DEFAULT 0,
  projects_viewed integer DEFAULT 0,
  budget_min_cr double precision,
  budget_max_cr double precision,
  CONSTRAINT callback_requests_pkey PRIMARY KEY (id)
);
CREATE TABLE public.payment_plans (
  id text NOT NULL,
  project_id text NOT NULL,
  plan_name text,
  milestones jsonb NOT NULL DEFAULT '[]'::jsonb,
  source text,
  source_url text,
  verified_at timestamp without time zone,
  verified_by text,
  notes text,
  created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp without time zone NOT NULL,
  plan_type text NOT NULL DEFAULT 'construction_linked'::text,
  sort_order integer NOT NULL DEFAULT 0,
  best_for text,
  booking_amount_lakh double precision,
  description text,
  discount_offered_pct double precision,
  down_payment_pct double precision,
  total_duration_months integer,
  watch_out text,
  CONSTRAINT payment_plans_pkey PRIMARY KEY (id),
  CONSTRAINT payment_plans_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.projects(id)
);
CREATE TABLE public.cost_sheets (
  id text NOT NULL,
  project_id text NOT NULL,
  base_price_per_sqft double precision,
  floor_rise_per_floor double precision,
  plc_charges jsonb NOT NULL DEFAULT '[]'::jsonb,
  parking_cost double precision,
  ifms double precision,
  club_membership double precision,
  other_charges jsonb NOT NULL DEFAULT '[]'::jsonb,
  gst_rate_pct double precision NOT NULL DEFAULT 5.0,
  stamp_duty_pct double precision NOT NULL DEFAULT 6.0,
  registration_pct double precision NOT NULL DEFAULT 1.0,
  assumptions ARRAY,
  verified_at timestamp without time zone,
  verified_by text,
  created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp without time zone NOT NULL,
  all_inclusive_per_sqft double precision,
  all_inclusive_price_cr double precision,
  base_cost_cr double precision,
  electricity_connection double precision,
  gst_applicable boolean,
  gst_note text,
  maintenance_psf_monthly double precision,
  water_sewer_connection double precision,
  CONSTRAINT cost_sheets_pkey PRIMARY KEY (id),
  CONSTRAINT cost_sheets_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.projects(id)
);
CREATE TABLE public.weekly_metrics_summary (
  id text NOT NULL,
  week_start timestamp without time zone NOT NULL,
  week_end timestamp without time zone NOT NULL,
  total_queries integer NOT NULL,
  unique_sessions integer NOT NULL,
  conversion_rate double precision NOT NULL,
  drop_off_rate double precision NOT NULL,
  avg_time_spent_s integer NOT NULL,
  top_sectors jsonb NOT NULL,
  intent_breakdown jsonb NOT NULL,
  budget_distribution jsonb NOT NULL,
  bhk_preferences jsonb NOT NULL,
  created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT weekly_metrics_summary_pkey PRIMARY KEY (id)
);
CREATE TABLE public.promotionals (
  id text NOT NULL,
  title text NOT NULL,
  description text,
  content text NOT NULL,
  link_type text,
  link_target text,
  image_url text,
  icon_url text,
  builder_id text,
  starts_at timestamp without time zone NOT NULL,
  ends_at timestamp without time zone NOT NULL,
  is_active boolean NOT NULL DEFAULT true,
  target_sectors ARRAY DEFAULT ARRAY[]::text[],
  target_bhk ARRAY DEFAULT ARRAY[]::integer[],
  impressions integer NOT NULL DEFAULT 0,
  clicks integer NOT NULL DEFAULT 0,
  conversions integer NOT NULL DEFAULT 0,
  created_by text,
  created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp without time zone NOT NULL,
  type USER-DEFINED NOT NULL,
  CONSTRAINT promotionals_pkey PRIMARY KEY (id)
);
CREATE TABLE public.promotional_interactions (
  id text NOT NULL,
  promotional_id text NOT NULL,
  session_id text,
  user_id text,
  guest_token text,
  interaction_type text NOT NULL,
  converted_project_id text,
  created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT promotional_interactions_pkey PRIMARY KEY (id),
  CONSTRAINT promotional_interactions_promotional_id_fkey FOREIGN KEY (promotional_id) REFERENCES public.promotionals(id)
);
CREATE TABLE public.builder_news (
  id text NOT NULL,
  builder_id text NOT NULL,
  title text NOT NULL,
  description text NOT NULL,
  image_url text,
  link_type text,
  link_target text,
  submitted_by text,
  approved_by text,
  approval_notes text,
  run_as_promo boolean NOT NULL DEFAULT false,
  promo_id text,
  archived_at timestamp without time zone,
  created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  published_at timestamp without time zone,
  status USER-DEFINED NOT NULL,
  CONSTRAINT builder_news_pkey PRIMARY KEY (id),
  CONSTRAINT builder_news_builder_id_fkey FOREIGN KEY (builder_id) REFERENCES public.builders(id)
);
CREATE TABLE public.builder_application_forms (
  id text NOT NULL,
  name text NOT NULL,
  cin text NOT NULL,
  email text NOT NULL,
  phone text NOT NULL,
  landline text,
  website text,
  headquarters text,
  logo_url text,
  description text,
  legal_entities jsonb,
  executives jsonb,
  projects ARRAY,
  delivery_track text,
  ip_address text NOT NULL,
  user_agent text NOT NULL,
  submitted_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  reviewed_by text,
  review_notes text,
  linked_builder text,
  status USER-DEFINED NOT NULL,
  CONSTRAINT builder_application_forms_pkey PRIMARY KEY (id)
);
CREATE TABLE public.builder_accounts (
  id text NOT NULL,
  builder_id text NOT NULL,
  user_id text,
  email text NOT NULL,
  password_hash text,
  auth_method text NOT NULL,
  last_login timestamp without time zone,
  last_activity timestamp without time zone,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp without time zone NOT NULL,
  CONSTRAINT builder_accounts_pkey PRIMARY KEY (id),
  CONSTRAINT builder_accounts_builder_id_fkey FOREIGN KEY (builder_id) REFERENCES public.builders(id)
);
CREATE TABLE public.builder_leads (
  id text NOT NULL,
  builder_id text NOT NULL,
  project_id text,
  lead_type text NOT NULL,
  name text,
  email text,
  phone text,
  message text,
  source_session text,
  source_intent jsonb,
  assigned_to text,
  notes text,
  contacted_at timestamp without time zone,
  converted_at timestamp without time zone,
  created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp without time zone NOT NULL,
  status USER-DEFINED NOT NULL,
  CONSTRAINT builder_leads_pkey PRIMARY KEY (id),
  CONSTRAINT builder_leads_builder_id_fkey FOREIGN KEY (builder_id) REFERENCES public.builders(id)
);
CREATE TABLE public.builder_analytics (
  id text NOT NULL,
  builder_id text NOT NULL,
  date timestamp without time zone NOT NULL,
  leads_generated integer NOT NULL DEFAULT 0,
  callbacks_requested integer NOT NULL DEFAULT 0,
  site_visits_requested integer NOT NULL DEFAULT 0,
  impressions integer NOT NULL DEFAULT 0,
  clicks_on_promo integer NOT NULL DEFAULT 0,
  conversions_from_promo integer NOT NULL DEFAULT 0,
  projects_viewed integer NOT NULL DEFAULT 0,
  projects_saved integer NOT NULL DEFAULT 0,
  created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT builder_analytics_pkey PRIMARY KEY (id)
);
CREATE TABLE public.builder_themes (
  id text NOT NULL,
  builder_id text NOT NULL,
  primary_color text NOT NULL,
  secondary_color text,
  logo_url text,
  favicon_url text,
  active_from timestamp without time zone NOT NULL,
  active_until timestamp without time zone,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT builder_themes_pkey PRIMARY KEY (id),
  CONSTRAINT builder_themes_builder_id_fkey FOREIGN KEY (builder_id) REFERENCES public.builders(id)
);
CREATE TABLE public.ai_usage_events (
  id text NOT NULL,
  user_id text,
  session_id text,
  provider text NOT NULL,
  model text NOT NULL,
  prompt_tokens integer NOT NULL,
  completion_tokens integer NOT NULL,
  cost_usd numeric NOT NULL,
  endpoint text NOT NULL,
  created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT ai_usage_events_pkey PRIMARY KEY (id)
);
CREATE TABLE public.shared_shortlists (
  id text NOT NULL,
  project_slugs ARRAY NOT NULL DEFAULT ARRAY[]::text[],
  created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  expires_at timestamp without time zone NOT NULL DEFAULT (now() + '30 days'::interval),
  CONSTRAINT shared_shortlists_pkey PRIMARY KEY (id)
);
CREATE TABLE public.price_history (
  id text NOT NULL,
  project_id text NOT NULL,
  recorded_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  price_per_sqft double precision,
  total_price_cr double precision,
  source text NOT NULL DEFAULT 'monthly_auto_snapshot'::text,
  bhk integer,
  event_note text,
  quarter_label text,
  CONSTRAINT price_history_pkey PRIMARY KEY (id),
  CONSTRAINT price_history_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.projects(id)
);
CREATE TABLE public.construction_milestones (
  id text NOT NULL,
  project_id text NOT NULL,
  name text NOT NULL,
  status USER-DEFINED NOT NULL DEFAULT 'upcoming'::"ConstructionStatus",
  completed_at timestamp without time zone,
  photo_urls ARRAY DEFAULT ARRAY[]::text[],
  sort_order integer NOT NULL DEFAULT 0,
  created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp without time zone NOT NULL,
  actual_start timestamp without time zone,
  completion_pct integer,
  critical_path boolean NOT NULL DEFAULT false,
  date_label text,
  is_payment_trigger boolean NOT NULL DEFAULT false,
  planned_end timestamp without time zone,
  planned_start timestamp without time zone,
  stage_code text,
  tower text,
  verified_by_source text,
  CONSTRAINT construction_milestones_pkey PRIMARY KEY (id),
  CONSTRAINT construction_milestones_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.projects(id)
);
CREATE TABLE public.builder_delivery_records (
  id text NOT NULL,
  builder_id text NOT NULL,
  project_name text NOT NULL,
  promised_date timestamp without time zone NOT NULL,
  actual_date timestamp without time zone,
  created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT builder_delivery_records_pkey PRIMARY KEY (id),
  CONSTRAINT builder_delivery_records_builder_id_fkey FOREIGN KEY (builder_id) REFERENCES public.builders(id)
);
CREATE TABLE public.construction_updates (
  id text NOT NULL,
  project_id text NOT NULL,
  title text NOT NULL,
  description text,
  update_date timestamp without time zone NOT NULL,
  quarter_label text,
  completion_pct integer,
  photo_urls ARRAY DEFAULT ARRAY[]::text[],
  source text,
  verified_by text,
  created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp without time zone NOT NULL,
  CONSTRAINT construction_updates_pkey PRIMARY KEY (id),
  CONSTRAINT construction_updates_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.projects(id)
);
CREATE TABLE public.project_lifecycle_updates (
  id text NOT NULL,
  project_id text NOT NULL,
  update_type text NOT NULL,
  title text NOT NULL,
  description text,
  update_date timestamp without time zone NOT NULL,
  impact text,
  source text,
  verified_by text,
  affects_pricing boolean NOT NULL DEFAULT false,
  affects_recommendation boolean NOT NULL DEFAULT false,
  legal_flag_cleared boolean NOT NULL DEFAULT false,
  maintenance_fee_monthly_psf double precision,
  maintenance_fee_previous double precision,
  note text,
  created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp without time zone NOT NULL,
  CONSTRAINT project_lifecycle_updates_pkey PRIMARY KEY (id),
  CONSTRAINT project_lifecycle_updates_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.projects(id)
);
CREATE TABLE public.sector_intelligence (
  id text NOT NULL,
  city text NOT NULL,
  sector text NOT NULL,
  sector_overview text,
  sector_stage text,
  dominant_segment text,
  avg_price_per_sqft double precision,
  price_5yr_cagr_pct double precision,
  rental_yield_pct double precision,
  avg_rent_3bhk_monthly double precision,
  sector_strengths ARRAY,
  sector_weaknesses ARRAY,
  who_should_buy text,
  who_should_avoid text,
  infrastructure_pipeline jsonb,
  last_verified_at timestamp without time zone,
  verified_by text,
  created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp without time zone NOT NULL,
  CONSTRAINT sector_intelligence_pkey PRIMARY KEY (id)
);
CREATE TABLE public.channel_partners (
  id text NOT NULL,
  name text NOT NULL,
  slug text NOT NULL,
  type text NOT NULL,
  description text,
  website text,
  phone text,
  email text,
  operating_cities ARRAY DEFAULT ARRAY[]::text[],
  primary_contact text,
  contact_phone text,
  contact_email text,
  is_verified boolean NOT NULL DEFAULT false,
  verification_date timestamp without time zone,
  total_leads integer NOT NULL DEFAULT 0,
  total_conversions integer NOT NULL DEFAULT 0,
  conversion_rate_pct double precision,
  rera_compliant boolean NOT NULL DEFAULT false,
  credai_member boolean NOT NULL DEFAULT false,
  specializations ARRAY DEFAULT ARRAY[]::text[],
  commission_rate_pct double precision,
  payment_terms text,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp without time zone NOT NULL,
  CONSTRAINT channel_partners_pkey PRIMARY KEY (id)
);
CREATE TABLE public.channel_leads (
  id text NOT NULL,
  partner_id text NOT NULL,
  user_id text,
  name text NOT NULL,
  email text NOT NULL,
  phone text NOT NULL,
  interested_sectors ARRAY DEFAULT ARRAY[]::text[],
  budget_range text,
  interested_bhk ARRAY DEFAULT ARRAY[]::integer[],
  status text NOT NULL DEFAULT 'new'::text,
  conversion_date timestamp without time zone,
  notes text,
  created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp without time zone NOT NULL,
  CONSTRAINT channel_leads_pkey PRIMARY KEY (id)
);